import { sqlMigration } from './types.ts';

export const planningMigration = sqlMigration(2, 'planning', [
  `CREATE TABLE areas (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT,
    status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE goals (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    area_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    motivation TEXT,
    status TEXT NOT NULL CHECK (status IN ('active', 'paused', 'completed', 'abandoned')),
    horizon TEXT NOT NULL CHECK (horizon IN ('month', 'quarter', 'year', 'someday')),
    target_date TEXT,
    completed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (area_id) REFERENCES areas(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE milestones (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    goal_id TEXT NOT NULL,
    title TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'cancelled')),
    target_date TEXT,
    completed_at TEXT,
    sort_order INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE routines (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    title TEXT NOT NULL,
    notes TEXT,
    schedule_json TEXT NOT NULL,
    time_zone TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'paused', 'archived')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE routine_check_ins (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    routine_id TEXT NOT NULL,
    date TEXT NOT NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('completed', 'skipped', 'missed')),
    recorded_at TEXT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (routine_id) REFERENCES routines(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE tasks (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    title TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
    priority TEXT NOT NULL CHECK (priority IN ('none', 'low', 'medium', 'high')),
    due_date TEXT,
    scheduled_time TEXT,
    time_zone TEXT,
    completed_at TEXT,
    area_id TEXT,
    goal_id TEXT,
    parent_task_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (area_id) REFERENCES areas(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE plan_blocks (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    time_zone TEXT NOT NULL,
    title TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL CHECK (status IN ('planned', 'completed', 'cancelled')),
    task_id TEXT,
    routine_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (routine_id) REFERENCES routines(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE tags (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE task_tags (
    task_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (task_id, tag_id),
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE
  )`,
  `CREATE TABLE reflections (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('day', 'week', 'goal')),
    scope_id TEXT,
    period_start TEXT NOT NULL,
    body TEXT NOT NULL,
    mood TEXT CHECK (mood IN ('low', 'steady', 'good', 'great')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0),
    deleted_at TEXT,
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT
  )`,
  `CREATE TABLE local_changes (
    id TEXT PRIMARY KEY NOT NULL,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('user_profile', 'workspace', 'task', 'plan_block', 'routine', 'routine_check_in', 'goal', 'milestone', 'area', 'tag', 'reflection', 'app_settings')),
    entity_id TEXT NOT NULL,
    entity_revision INTEGER NOT NULL CHECK (entity_revision > 0),
    operation TEXT NOT NULL CHECK (operation IN ('upsert', 'delete')),
    state TEXT NOT NULL CHECK (state IN ('pending', 'processing', 'failed')),
    attempt_count INTEGER NOT NULL CHECK (attempt_count >= 0),
    last_attempt_at TEXT,
    error_code TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision > 0)
  )`,
  `CREATE INDEX areas_workspace_updated_idx ON areas(workspace_id, updated_at DESC, id ASC)`,
  `CREATE INDEX goals_workspace_updated_idx ON goals(workspace_id, updated_at DESC, id ASC)`,
  `CREATE INDEX milestones_goal_order_idx ON milestones(goal_id, sort_order ASC, id ASC)`,
  `CREATE INDEX routines_workspace_updated_idx ON routines(workspace_id, updated_at DESC, id ASC)`,
  `CREATE UNIQUE INDEX routine_check_in_day_idx ON routine_check_ins(routine_id, date) WHERE deleted_at IS NULL`,
  `CREATE INDEX tasks_workspace_updated_idx ON tasks(workspace_id, updated_at DESC, id ASC)`,
  `CREATE INDEX tasks_due_date_idx ON tasks(workspace_id, due_date ASC, id ASC) WHERE deleted_at IS NULL`,
  `CREATE INDEX plan_blocks_day_idx ON plan_blocks(workspace_id, date ASC, start_time ASC, id ASC)`,
  `CREATE INDEX tags_workspace_updated_idx ON tags(workspace_id, updated_at DESC, id ASC)`,
  `CREATE UNIQUE INDEX active_tag_name_idx ON tags(workspace_id, name) WHERE deleted_at IS NULL`,
  `CREATE INDEX reflections_period_idx ON reflections(workspace_id, period_start DESC, id ASC)`,
  `CREATE INDEX local_changes_queue_idx ON local_changes(state, created_at ASC, id ASC)`,
]);
