import { sqlMigration } from './types.ts';

export const remindersCalendarMigration = sqlMigration(
  7,
  'reminders_calendar',
  [
    `ALTER TABLE app_settings ADD COLUMN notification_titles_enabled INTEGER NOT NULL DEFAULT 0 CHECK (notification_titles_enabled IN (0, 1))`,
    `ALTER TABLE app_settings ADD COLUMN quiet_hours_enabled INTEGER NOT NULL DEFAULT 0 CHECK (quiet_hours_enabled IN (0, 1))`,
    `ALTER TABLE app_settings ADD COLUMN quiet_hours_start TEXT NOT NULL DEFAULT '22:00'`,
    `ALTER TABLE app_settings ADD COLUMN quiet_hours_end TEXT NOT NULL DEFAULT '07:00'`,
    `ALTER TABLE app_settings ADD COLUMN device_calendar_id TEXT`,
    `ALTER TABLE app_settings ADD COLUMN device_calendar_name TEXT`,
    `CREATE TABLE reminder_intents (
      id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT NOT NULL,
      entity_type TEXT NOT NULL CHECK (entity_type IN ('task', 'plan_block', 'routine', 'goal')),
      entity_id TEXT NOT NULL,
      trigger_kind TEXT NOT NULL CHECK (trigger_kind IN ('relative', 'absolute')),
      offset_minutes INTEGER,
      absolute_at TEXT,
      enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      revision INTEGER NOT NULL CHECK (revision > 0),
      deleted_at TEXT,
      CHECK ((trigger_kind = 'relative' AND offset_minutes IS NOT NULL AND offset_minutes BETWEEN 0 AND 10080 AND absolute_at IS NULL) OR (trigger_kind = 'absolute' AND offset_minutes IS NULL AND absolute_at IS NOT NULL)),
      FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT
    )`,
    `CREATE TABLE device_notification_schedules (
      id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT NOT NULL,
      reminder_intent_id TEXT NOT NULL,
      occurrence_key TEXT NOT NULL,
      notification_identifier TEXT,
      scheduled_for TEXT,
      state TEXT NOT NULL CHECK (state IN ('scheduled', 'skipped', 'error')),
      reason TEXT,
      source_revision INTEGER NOT NULL CHECK (source_revision > 0),
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      revision INTEGER NOT NULL CHECK (revision > 0),
      deleted_at TEXT,
      FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
      FOREIGN KEY (reminder_intent_id, workspace_id) REFERENCES reminder_intents(id, workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT
    )`,
    `CREATE TABLE device_calendar_events (
      id TEXT PRIMARY KEY NOT NULL,
      workspace_id TEXT NOT NULL,
      plan_block_id TEXT NOT NULL,
      calendar_id TEXT NOT NULL,
      event_id TEXT NOT NULL,
      source_revision INTEGER NOT NULL CHECK (source_revision > 0),
      source_fingerprint TEXT NOT NULL,
      state TEXT NOT NULL CHECK (state IN ('active', 'missing', 'external_change')),
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      revision INTEGER NOT NULL CHECK (revision > 0),
      deleted_at TEXT,
      FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE CASCADE ON DELETE RESTRICT,
      FOREIGN KEY (plan_block_id, workspace_id) REFERENCES plan_blocks(id, workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT
    )`,
    `CREATE UNIQUE INDEX reminder_intents_id_workspace_idx ON reminder_intents(id, workspace_id)`,
    `CREATE UNIQUE INDEX plan_blocks_id_workspace_phase8_idx ON plan_blocks(id, workspace_id)`,
    `CREATE UNIQUE INDEX reminder_intents_entity_idx ON reminder_intents(workspace_id, entity_type, entity_id) WHERE deleted_at IS NULL`,
    `CREATE INDEX reminder_intents_reconcile_idx ON reminder_intents(workspace_id, enabled, updated_at ASC, id ASC) WHERE deleted_at IS NULL`,
    `CREATE UNIQUE INDEX notification_schedule_occurrence_idx ON device_notification_schedules(reminder_intent_id, occurrence_key) WHERE deleted_at IS NULL`,
    `CREATE INDEX notification_schedule_workspace_idx ON device_notification_schedules(workspace_id, state, scheduled_for ASC, id ASC) WHERE deleted_at IS NULL`,
    `CREATE UNIQUE INDEX calendar_event_block_idx ON device_calendar_events(workspace_id, plan_block_id) WHERE deleted_at IS NULL`,
    `CREATE INDEX calendar_event_workspace_idx ON device_calendar_events(workspace_id, state, updated_at ASC, id ASC) WHERE deleted_at IS NULL`,
  ],
);
