import type { TranslationCatalog } from './catalogs.ts';

export const am = {
  common: {
    back: 'ተመለስ', cancel: 'ሰርዝ', close: 'ዝጋ', continue: 'ቀጥል', create: 'ፍጠር', delete: 'አጥፋ', done: 'ተጠናቋል', edit: 'አርትዕ', goBack: 'ወደ ኋላ ተመለስ', keep: 'አቆይ', loading: 'በመጫን ላይ', noNotes: 'ማስታወሻ የለም', none: 'የለም', refresh: 'አድስ', retry: 'እንደገና ሞክር', save: 'አስቀምጥ', skip: 'ዝለል', today: 'ዛሬ', tomorrow: 'ነገ', yesterday: 'ትናንት', active: 'ንቁ', paused: 'ለጊዜው ቆሟል', archived: 'ተመዝግቧል', planned: 'የታቀደ', completed: 'ተጠናቋል', cancelled: 'ተሰርዟል', pending: 'በመጠባበቅ ላይ', inProgress: 'በሂደት ላይ', skipped: 'ተዘሏል', anyTime: 'ዛሬ በማንኛውም ጊዜ', minuteOne: '{{count}} ደቂቃ', minuteOther: '{{count}} ደቂቃዎች', hourOne: '{{count}} ሰዓት', hourOther: '{{count}} ሰዓታት',
  },
  launch: { starting: 'Planora እየተጀመረ ነው', tagline: 'ለሚያስፈልግዎ ነገር ቦታ ይስጡ።', storage: 'የአካባቢ ማከማቻ እየተዘጋጀ ነው።', account: 'መለያዎ እየተመለሰ ነው።', preferences: 'ምርጫዎችዎ እየተጫኑ ናቸው።', workspace: 'የእቅድ ቦታዎ እየተዘጋጀ ነው።' },
  tabs: { today: 'ዛሬ', planner: 'እቅድ', goals: 'ግቦች', insights: 'ግንዛቤዎች', settings: 'ቅንብሮች' },
  auth: {
    chooseTitle: 'ለዛሬ የሚስማማዎትን ይምረጡ', chooseDescription: 'Planoraን በመሣሪያዎ ብቻ ይጠቀሙ ወይም ለመገለጫና መልሶ ማግኘት መለያ ያክሉ። የእቅድ ይዘት በዚህ መሣሪያ ላይ ይቆያል።', localTitle: 'በመሣሪያው ብቻ ቀጥል', localDescription: 'መለያ አያስፈልግም። የአካባቢ የእቅድ ውሂብዎ ከመስመር ውጭ ዝግጁ ሆኖ ይቆያል።', accountTitle: 'አማራጭ መለያ', accountDescription: 'መገለጫ ይፍጠሩ ወይም ይግቡ። ይህ የአካባቢ የእቅድ መዝገቦችን አይሰቅልም፣ አያዋህድም ወይም አይተካም።', accountUnavailable: 'በዚህ ስሪት የመለያ አገልግሎቶች አልተዘጋጁም። የአካባቢ አጠቃቀም ይገኛል።', createAccount: 'መለያ ፍጠር', signIn: 'ግባ', signInTitle: 'እንኳን ደህና መጡ', signInDescription: 'ወደ አማራጭ የPlanora መለያዎ ይግቡ። የአካባቢ የእቅድ ቦታዎ ተለይቶና ዝግጁ ሆኖ ይቆያል።', createTitle: 'መለያዎን ይፍጠሩ', createDescription: 'ለመግባትና መልሶ ለማግኘት ቀላል መገለጫ ይፍጠሩ። የእቅድ ይዘት ወደ መለያ አገልግሎት አይላክም።', displayName: 'የሚታይ ስም', displayNamePlaceholder: 'እንዴት እንዲጠሩ ይፈልጋሉ', email: 'ኢሜይል', emailPlaceholder: 'you@example.com', password: 'የይለፍ ቃል', confirmPassword: 'የይለፍ ቃል ያረጋግጡ', newPassword: 'አዲስ የይለፍ ቃል', confirmNewPassword: 'አዲሱን የይለፍ ቃል ያረጋግጡ', alreadyAccount: 'መለያ አለዎት? ይግቡ', createInstead: 'መለያ ይፍጠሩ', forgotPassword: 'የይለፍ ቃል ረሱ?', recoveryEyebrow: 'መለያ መልሶ ማግኘት', recoveryTitle: 'የይለፍ ቃልዎን ይቀይሩ', recoveryDescription: 'መለያ መኖሩን ሳንገልጽ የመልሶ ማግኛ መልዕክት እንድንጠይቅ ኢሜይልዎን ያስገቡ።', sendRecovery: 'የመልሶ ማግኛ መመሪያ ላክ', secureRecovery: 'ደህንነቱ የተጠበቀ መልሶ ማግኘት', choosePassword: 'አዲስ የይለፍ ቃል ይምረጡ', choosePasswordDescription: 'ለመለያዎ አዲስ የይለፍ ቃል ይምረጡ። ይህ የአካባቢ የእቅድ ውሂብን አይቀይርም ወይም አያጠፋም።', savePassword: 'አዲስ የይለፍ ቃል አስቀምጥ', checkEmailEyebrow: 'ኢሜይልዎን ይመልከቱ', checkEmailTitle: 'አንድ ተጨማሪ እርምጃ', checkEmailDescription: 'አድራሻው የተጠየቀውን መልዕክት መቀበል ከቻለ፣ ለመቀጠል በመልዕክቱ ያለውን አገናኝ ይከተሉ።', inboxTitle: 'ቀጣዩ እርምጃ በገቢ መልዕክትዎ ውስጥ ነው', returnSignIn: 'ወደ መግቢያ ተመለስ', recoveryValidating: 'Planora የግል የክፍለ ጊዜ ዝርዝሮችን ሳያሳይ የመልሶ ማግኛ አገናኙን እያረጋገጠ ነው።', requestNewLink: 'አዲስ አገናኝ ጠይቅ', issueEyebrow: 'ሊስተካከል የሚችል ችግር', issueTitle: 'ሌላ መንገድ እንሞክር', issueDescription: 'የመለያ ጥያቄው አልተጠናቀቀም፣ ነገር ግን የአካባቢ የPlanora ውሂብዎ ደህንነቱ የተጠበቀና ዝግጁ ነው።', accountOptions: 'ወደ መለያ አማራጮች ተመለስ', profileEyebrow: 'የመለያ መገለጫ', editProfile: 'መገለጫ አርትዕ', profileDescription: 'ይህ ቀላል የመለያ መገለጫ ከአካባቢ የእቅድ መዝገቦችዎ የተለየ ነው።', profileScope: 'የመገለጫ ወሰን', saveProfile: 'መገለጫ አስቀምጥ', signOut: 'ውጣ', signOutTitle: 'ከመለያዎ ይውጡ?', signOutDescription: 'የእቅድ ውሂብዎ በዚህ መሣሪያ ላይ ይቆያል እና ከወጡ በኋላም ይገኛል።', accountLabel: 'መለያ', accountSettingsDescription: 'የመለያ ባህሪያት አማራጭ ሲሆኑ ከአካባቢ የእቅድ ውሂብ ተለይተው ይቆያሉ።', planoraAccount: 'የPlanora መለያ', localOnly: 'በመሣሪያው ብቻ', localOnlyDescription: 'ዋና የእቅድ ትሮችን ለመጠቀም መለያ አያስፈልግም።', emailVerified: 'ኢሜይል ተረጋግጧል', emailPending: 'የኢሜይል ማረጋገጫ በመጠባበቅ ላይ', viewOnboarding: 'መግቢያውን እንደገና ይመልከቱ',
    newToAccount: 'የመለያ ባህሪያትን አዲስ ነዎት?',
    passwordPrivacy: 'የይለፍ ቃልዎ በደህንነት ወደ መለያ አቅራቢው ይላካል እና በPlanora የአካባቢ የእቅድ ውሂብ ጎታ ውስጥ ፈጽሞ አይቀመጥም።',
    recoveryPrivacy: 'ለግላዊነት፣ የማረጋገጫ ገጹ ለሁሉም ትክክለኛ የኢሜይል ቅርጸቶች አንድ ነው።',
    showPassword: 'የይለፍ ቃል አሳይ', hidePassword: 'የይለፍ ቃል ደብቅ',
  },
  onboarding: {
    pageOneEyebrow: 'የተረጋጋ ጅምር', pageOneTitle: 'ለመተንፈስ ቦታ ያለው ቀንዎ', pageOneDescription: 'Planora ሌሎች የእቅድ ቦታዎችን ቅርብ አድርጎ ተግባራትንና ልማዶችን በተረጋጋ ዕለታዊ እይታ ያሰባስባል።', pageOneDetail: 'መለያ ሳይፈጥሩ ተግባራትን ያክሉ እና ልማዶችን ይመዝግቡ።', pageTwoEyebrow: 'በነባሪ አካባቢያዊ', pageTwoTitle: 'ኔትወርክ ባይኖርም ዝግጁ', pageTwoDescription: 'የእቅድ መሠረትዎ በዚህ መሣሪያ ላይ ይቀመጣል እና ከመስመር ውጭ ይገኛል። የአካባቢ እርምጃዎች የመለያ አገልግሎት አይጠብቁም።', pageTwoDetail: 'የአካባቢ ውሂብ ከዳግም ማስነሳት በኋላ ይቆያል እና ከመለያ ክፍለ ጊዜ የተለየ ነው።', pageThreeEyebrow: 'ምርጫው የእርስዎ ነው', pageThreeTitle: 'መለያ አማራጭ ነው', pageThreeDescription: 'ለመገለጫና መልሶ ማግኘት መለያ ይፍጠሩ ወይም በመሣሪያው ብቻ ይቀጥሉ። የእቅድ ይዘት አይሰቀልም ወይም አይመሳሰልም።', pageThreeDetail: 'የአካባቢ መለያዎችን ሳይቀይሩ በኋላ ከቅንብሮች መግባት ይችላሉ።', close: 'መግቢያውን ዝጋ', skip: 'መግቢያውን ዝለል', step: 'ደረጃ {{current}} ከ{{total}}', stepAnnouncement: 'ደረጃ {{current}} ከ{{total}}። {{title}}', startLocally: 'በመሣሪያው ጀምር',
  },
  today: {
    greeting: 'የዛሬ ግልጽ እይታ', subtitle: 'የሚያስፈልግዎትን ይምረጡ፣ ከዚያ ለቀኑ ለውጥ ቦታ ይተዉ።', quickPlaceholder: 'ለዛሬ ተግባር ያክሉ', quickLabel: 'ተግባር በፍጥነት ያክሉ', quickHint: 'ዛሬ የሚደርስ ተግባር ይፈጥራል', add: 'ጨምር', progress: '{{completed}} ከ{{total}} ተጠናቋል', workload: '{{planned}} ታቅዷል · {{remaining}} ቀርቷል', nextUp: 'ቀጣይ', priority: 'ቅድሚያ እና ያለፈባቸው', remaining: 'የዛሬ ተግባራት', routines: 'የታቀዱ ልማዶች', agenda: 'የቀን መርሐግብር ቅድመ እይታ', completed: 'የተጠናቀቀ', showCompleted: 'የተጠናቀቁትን አሳይ', hideCompleted: 'የተጠናቀቁትን ደብቅ', quietEmpty: 'አሁን ትኩረትዎን የሚፈልግ ነገር የለም።', noPriority: 'ቅድሚያ ያለው ወይም ጊዜው ያለፈ ተግባር የለም።', noRemaining: 'ለዛሬ የቀረ ተግባር የለም።', noRoutines: 'ዛሬ የታቀደ ልማድ የለም።', noAgenda: 'እስካሁን የታቀደ የጊዜ ክፍል የለም።', allTasks: 'ሁሉም ተግባራት', allRoutines: 'ልማዶች', openPlanner: 'እቅድ ክፈት', moreActions: 'ተጨማሪ እርምጃዎች', loading: 'ቀንዎ እየተጫነ ነው።', refreshTitle: 'ቀንዎ መታደስ አለበት', failed: 'ቀንዎን መጫን አልተቻለም።', completedToday: 'ዛሬ ተጠናቋል', skippedToday: 'ዛሬ ተዘሏል', markComplete: 'እንደተጠናቀቀ ምልክት አድርግ', markSkipped: 'እንደተዘለለ ምልክት አድርግ', undo: 'መዝገቡን ቀልብስ', overdue: 'ጊዜው ያለፈ', dueToday: 'ዛሬ የሚደርስ', unscheduled: 'ገቢ ሳጥን',
  },
  tasks: {
    title: 'ሁሉም ተግባራት', new: 'አዲስ ተግባር', details: 'የተግባር ዝርዝር', createDescription: 'የሚያስፈልግዎትን ያክሉ፣ ጊዜውን መወሰን ካገዘ ብቻ ይቀይሩ።', editDescription: 'የአካባቢ መለያውን ሳይቀይሩ ተግባሩን ያዘምኑ።', loading: 'የተግባር ዝርዝር እየተጫነ ነው።', refreshTitle: 'የተግባር ዝርዝር መታደስ አለበት', listRefresh: 'የተግባር ዝርዝርዎ መታደስ አለበት', notLoaded: 'ተግባሩን መጫን አልተቻለም።', unavailable: 'ተግባሩ አይገኝም', unavailableDescription: 'ተወግዶ ወይም ተቀይሮ ሊሆን ይችላል። ወደ ዛሬ ተመልሰው ያድሱ።', emptyTitle: 'እስካሁን ተግባር የለም', emptyDescription: 'ፈጣን ግቤቶችና ሙሉ ተግባራት እዚህ ይገኛሉ።', createAction: 'ተግባር ፍጠር', actions: 'የተግባር እርምጃዎች', complete: 'ተግባር አጠናቅ', reopen: 'ተግባር እንደገና ክፈት', cancel: 'ተግባር ሰርዝ', delete: 'ተግባር አጥፋ', cancelTitle: 'ተግባሩ ይሰረዝ?', cancelDescription: 'ተግባሩ ከንቁ የቀን ክፍሎች ይወጣል እና በኋላ እንደገና ሊከፈት ይችላል።', keep: 'ተግባሩን አቆይ', deleteTitle: 'ተግባሩ ይጥፋ?', deleteDescription: 'ይህ ተግባሩን ከዕለታዊ እይታዎች ያስወግዳል። እዚህ ይህን መቀልበስ አይቻልም።', overdue: 'ጊዜው ያለፈ', upcoming: 'መጪ', unscheduled: 'ያልታቀደ', opensDetails: 'የተግባር ዝርዝርን ይከፍታል', titleField: 'ርዕስ', notesField: 'ማስታወሻዎች', priorityField: 'ቅድሚያ', statusField: 'ሁኔታ', dueDate: 'የመድረሻ ቀን', dueDateHint: 'YYYY-MM-DD ይጠቀሙ ወይም ባዶ ይተዉ።', scheduledTime: 'የታቀደ ጊዜ', timeHint: 'የ24 ሰዓት HH:MM ቅርጸት ይጠቀሙ ወይም ባዶ ይተዉ።', priorityNone: 'ቅድሚያ የለም', priorityLow: 'ዝቅተኛ ቅድሚያ', priorityMedium: 'መካከለኛ ቅድሚያ', priorityHigh: 'ከፍተኛ ቅድሚያ',
  },
  routines: {
    title: 'ልማዶች', new: 'አዲስ ልማድ', details: 'የልማድ ዝርዝር', description: 'ያለ ማስታወሻ ወይም ውጤት ቀላል ዕለታዊ ወይም ሳምንታዊ ልማድ ይገንቡ።', loading: 'የልማድ ዝርዝር እየተጫነ ነው።', refreshTitle: 'የልማድ ዝርዝር መታደስ አለበት', listRefresh: 'የልማድ ዝርዝርዎ መታደስ አለበት', notLoaded: 'ልማዱን መጫን አልተቻለም።', unavailable: 'ልማዱ አይገኝም', unavailableDescription: 'ወደ ዛሬ ተመልሰው የአካባቢ የእቅድ ውሂብዎን ያድሱ።', emptyTitle: 'እስካሁን ልማድ የለም', emptyDescription: 'ዕለታዊ ልማድ ይፍጠሩ ወይም የሚስማሙትን የሳምንት ቀናት ይምረጡ።', createAction: 'ልማድ ፍጠር', opensDetails: 'የልማድ ዝርዝርን ይከፍታል', schedule: 'መርሐግብር', everyDay: 'በየቀኑ', selectedDays: 'የተመረጡ ቀናት', weekdays: 'የሳምንት ቀናት', preferredTime: 'የተመረጠ ጊዜ', state: 'የልማድ ሁኔታ',
  },
  planner: {
    title: 'እቅድ', day: 'ቀን', week: 'ሳምንት', previousDay: 'ያለፈው ቀን', nextDay: 'ቀጣዩ ቀን', previousWeek: 'ያለፈው ሳምንት', nextWeek: 'ቀጣዩ ሳምንት', currentWeek: 'የአሁኑ ሳምንት', date: 'ቀን', timeline: 'ዕለታዊ የጊዜ መስመር', newBlock: 'አዲስ የጊዜ ክፍል', editBlock: 'የጊዜ ክፍል አርትዕ', blockDetails: 'የጊዜ ክፍል ዝርዝር', unscheduledTasks: 'ያልታቀዱ ተግባራት', scheduleTask: 'ተግባር አቅድ', noBlocks: 'ለዚህ ቀን የታቀደ የጊዜ ክፍል የለም።', noTasks: 'ሁሉም ሊሠሩ የሚችሉ ተግባራት የጊዜ ክፍል አላቸው።', workload: 'የሥራ ጫና', plannedMinutes: '{{duration}} ታቅዷል', remainingCapacity: '{{duration}} ቀርቷል', overCapacity: '{{duration}} ከዕለታዊ አቅምዎ በላይ', withinCapacity: 'በዕለታዊ አቅምዎ ውስጥ', overlapOne: '{{count}} መደራረብ', overlapOther: '{{count}} መደራረቦች', unscheduledOne: '{{count}} ያልታቀደ ተግባር', unscheduledOther: '{{count}} ያልታቀዱ ተግባራት', blockOne: '{{count}} ክፍል', blockOther: '{{count}} ክፍሎች', taskOne: '{{count}} ተግባር', taskOther: '{{count}} ተግባራት', overlapWarning: 'ይህ ክፍል ከሌላ ክፍል ጋር ይደራረባል። ማቆየት ወይም ጊዜውን መቀየር ይችላሉ።', overlapCounted: 'የተደራረቡ ክፍሎች በታቀደው ጊዜ ውስጥ ለየብቻ ይቆጠራሉ።', overloaded: 'ከአቅም በላይ', linkedTask: 'የተያያዘ ተግባር', linkedRoutine: 'የተያያዘ ልማድ', removeLink: 'ግንኙነት አስወግድ', completeBlock: 'ክፍሉን አጠናቅ', reopenBlock: 'ክፍሉን እንደገና ክፈት', cancelBlock: 'ክፍሉን ሰርዝ', deleteBlock: 'ክፍሉን አጥፋ', deleteTitle: 'የጊዜ ክፍሉ ይጥፋ?', deleteDescription: 'ይህ የታቀደውን የጊዜ ክፍል ብቻ ያስወግዳል። የተያያዙ ተግባራትና ልማዶች ይቆያሉ።', cancelTitle: 'የጊዜ ክፍሉ ይሰረዝ?', cancelDescription: 'የተሰረዙ ክፍሎች በታሪክ ውስጥ ይቆያሉ እና በአቅም ውስጥ አይቆጠሩም።', keepBlock: 'ክፍሉን አቆይ', startTime: 'የመጀመሪያ ጊዜ', endTime: 'የመጨረሻ ጊዜ', titleField: 'ርዕስ', notesField: 'ማስታወሻዎች', statusField: 'ሁኔታ', repeat: 'ድግግሞሽ', repeatNone: 'አይደገምም', repeatDaily: 'በየቀኑ', repeatWeekly: 'በየሳምንቱ', repeatInterval: 'የድግግሞሽ ርቀት', repeatEnd: 'ድግግሞሽ የሚያበቃበት ቀን', editOccurrence: 'ይህን ጊዜ አርትዕ', editFuture: 'ይህንና የወደፊት ጊዜያትን አርትዕ', recurrenceBounded: 'ድግግሞሾች በሚንቀሳቀስ የስምንት ሳምንት መስኮት ይዘጋጃሉ።', move: 'አንቀሳቅስ ወይም እንደገና አቅድ', selectedDay: 'የተመረጠ ቀን', currentTime: 'የአሁኑ ጊዜ', capacitySummary: '{{planned}} ታቅዷል፣ አቅም {{capacity}}', loading: 'መርሐግብርዎ እየተጫነ ነው።', refreshTitle: 'መርሐግብርዎ መታደስ አለበት',
  },
  settings: {
    eyebrow: 'የእርስዎ ቦታ', title: 'ቅንብሮች', description: 'Planora እንዴት እንደሚታይና እንደሚሠራ ከመጀመሪያው በተደራሽ ምርጫዎች ያስተካክሉ።', language: 'ቋንቋ', languageDescription: 'ለዚህ የአካባቢ መገለጫ የመተግበሪያ ቋንቋ ይምረጡ።', systemLanguage: 'የመሣሪያውን ቋንቋ ተጠቀም', directionRestart: 'የቀኝ ወደ ግራ አቀማመጥን በመተግበሪያው ሁሉ ለመተግበር Planoraን እንደገና ያስጀምሩ። Expo Go ይህን ምርጫ ሊመልስ ይችላል፤ የRTL ማረጋገጫ ለማድረግ የልማት ስሪት ይጠቀሙ።', planning: 'የእቅድ ምርጫዎች', planningDescription: 'የሥራ ጫናን ለማነጻጸር የተረጋጋ ዕለታዊ አቅም ይወስኑ።', capacity: 'ዕለታዊ አቅም በደቂቃ', capacityHint: 'ከ30 እስከ 1,440 ደቂቃ ይምረጡ።', saveCapacity: 'አቅም አስቀምጥ', saved: 'ምርጫው ተቀምጧል።',
  },
  storage: {
    title: 'ውሂብ እና ማከማቻ', description: 'የእቅድ መሠረትዎ በዚህ መሣሪያ ላይ ይኖራል።', localData: 'የአካባቢ ውሂብ', localReady: 'በዚህ መሣሪያ ላይ ይገኛል', localPreparing: 'ተደራሽነት እየተዘጋጀ ነው', offline: 'ከመስመር ውጭ ዝግጁነት', offlineReady: 'ከመስመር ውጭ ለመጠቀም ዝግጁ', offlinePreparing: 'ዝግጅት እየተጠናቀቀ ነው', state: 'የማከማቻ ሁኔታ', ready: 'ዝግጁ', preparing: 'በመዘጋጀት ላይ', errorTitle: 'የአካባቢ ማከማቻ ሌላ ሙከራ ይፈልጋል', retryLabel: 'የአካባቢ ማከማቻን እንደገና ለማዘጋጀት ሞክር',
  },
  validation: {
    taskTitle: 'የተግባር ርዕስ ያስገቡ።', blockTitle: 'የጊዜ ክፍል ርዕስ ያስገቡ።', routineTitle: 'የልማድ ርዕስ ያስገቡ።', titleLength: '200 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', notesLength: '4,000 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', date: 'በYYYY-MM-DD ቅርጸት ትክክለኛ ቀን ይጠቀሙ።', startDate: 'ትክክለኛ የመጀመሪያ ቀን ይጠቀሙ።', endDate: 'ትክክለኛ የመጨረሻ ቀን ይጠቀሙ።', time: 'በHH:MM ቅርጸት ትክክለኛ ጊዜ ይጠቀሙ።', startTime: 'በHH:MM ቅርጸት ትክክለኛ የመጀመሪያ ጊዜ ይጠቀሙ።', endTime: 'በHH:MM ቅርጸት ትክክለኛ የመጨረሻ ጊዜ ይጠቀሙ።', endAfterStart: 'የመጨረሻ ጊዜ ከመጀመሪያ ጊዜ በኋላ መሆን አለበት።', nonexistentTime: 'በዚህ ቀን የሚኖር የአካባቢ ጊዜ ይምረጡ።', scheduledNeedsDate: 'ለታቀደ ጊዜ የመድረሻ ቀን ይምረጡ።', weekdays: 'ቢያንስ አንድ የሳምንት ቀን ይምረጡ።', interval: 'የድግግሞሽ ርቀት ከ1 እስከ 365 መሆን አለበት።', capacity: 'ከ30 እስከ 1,440 ሙሉ ቁጥር ይምረጡ።', emailRequired: 'ኢሜይልዎን ያስገቡ።', emailComplete: 'ሙሉ የኢሜይል አድራሻ ያስገቡ።', passwordRequired: 'የይለፍ ቃልዎን ያስገቡ።', passwordLength: 'ቢያንስ ስምንት ቁምፊዎች ይጠቀሙ።', displayNameRequired: 'የሚታይ ስም ያስገቡ።', displayNameLength: '60 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።',
    passwordsMatch: 'የይለፍ ቃሎቹ አይመሳሰሉም።',
  },
  errors: {
    refreshDay: 'Planora ይህን ቀን ማደስ አልቻለም። የተቀመጠው የአካባቢ ውሂብዎ አልተቀየረም።', revision: 'ዝማኔዎ ከመቀመጡ በፊት ይህ ንጥል ተቀይሯል። ያድሱና እንደገና ይሞክሩ።', save: 'ያ ለውጥ ሊቀመጥ አልቻለም። ቀኑን ያድሱና እንደገና ይሞክሩ።', onboardingRead: 'Planora የመግቢያ ምርጫዎችን ማንበብ አልቻለም። የአካባቢ ውሂብዎ አሁንም ይገኛል።', onboardingSave: 'Planora ይህን ምርጫ ማስቀመጥ አልቻለም። እንደገና ይሞክሩ።', workspace: 'Planora የአካባቢ የእቅድ ቦታዎን ማዘጋጀት አልቻለም። ውሂብዎ አልተቀየረም።', generic: 'ትንሽ ይጠብቁና እንደገና ይሞክሩ።',
    invalidCredentials: 'ኢሜይሉ ወይም የይለፍ ቃሉ አልተቀበለም። ሁለቱንም ይፈትሹና ደግመው ይሞክሩ።', emailUnverified: 'ከመግባትዎ በፊት ኢሜይልዎን ያረጋግጡና ደግመው ይሞክሩ።', emailInUse: 'ይህ ኢሜይል ለአዲስ መለያ መጠቀም አይቻልም። ለመግባት ይሞክሩ።', weakPassword: 'ቢያንስ ስምንት ቁምፊ ያለው ጠንካራ የይለፍ ቃል ይምረጡ።', networkUnavailable: 'Planora የመለያ አገልግሎቱን ማግኘት አልቻለም። ግንኙነትዎን ይፈትሹና ደግመው ይሞክሩ።', rateLimited: 'ብዙ ሙከራዎች ተደርገዋል። ትንሽ ይጠብቁና ደግመው ይሞክሩ።', expiredLink: 'ይህ የመልሶ ማግኛ አገናኝ ከእንግዲህ ትክክለኛ አይደለም። አዲስ አገናኝ ይጠይቁ።', serviceUnavailable: 'የመለያ አገልግሎቶች ለጊዜው አይገኙም። የአካባቢ ውሂብዎ አልተነካም።', accountUnknown: 'በመለያ ጥያቄው ላይ ችግር ተፈጥሯል። የአካባቢ ውሂብዎ አልተነካም።', linkTask: 'ከዚህ የሥራ ቦታ የሚገኝ ተግባር ይምረጡ።', linkRoutine: 'ከዚህ የሥራ ቦታ የሚገኝ ልማድ ይምረጡ።', linkEither: 'ተግባር ወይም ልማድ ያገናኙ፣ ሁለቱንም አይደለም።', endBeforeStart: 'የመጨረሻ ቀን ከመጀመሪያ ቀን በፊት መሆን አይችልም።', recurrenceConflict: 'ይህ ድግግሞሽ ተቀይሯል። ያድሱና ደግመው ይሞክሩ።', recurrenceWindow: 'የድግግሞሽ መስኮቶች በ56 ቀናት የተገደቡ ናቸው።',
    scheduleRefresh: 'የጊዜ ሰሌዳዎን ማደስ አልተቻለም። የተቀመጠው የአካባቢ ውሂብ አልተቀየረም።', scheduleRevision: 'ማሻሻያዎ ከመቀመጡ በፊት ይህ የጊዜ ሰሌዳ ተቀይሯል። ያድሱና ደግመው ይሞክሩ።', scheduleSave: 'የጊዜ ሰሌዳውን ለውጥ ማስቀመጥ አልተቻለም። ያድሱና ደግመው ይሞክሩ።',
  },
  placeholders: {
    goalsDescription: 'የረጅም ጊዜ ፍላጎቶችን ወደሚታዩ ምዕራፎችና ተግባራዊ ቀጣይ እርምጃዎች ይቀይሩ።', goalsEmpty: 'ትርጉም ያለው እድገት እዚህ ይጀምራል', goalsEmptyDescription: 'የግብ መንገዶች፣ ምዕራፎችና የእድገት ምዝገባዎች ለተለየ የባህሪ ደረጃ ታቅደዋል።', insightsDescription: 'የግል ውሂብዎን ግልጽና የግል አድርገው ጠቃሚ ቅጦችን ይመልከቱ።', insightsEmpty: 'ቅጦችዎ ታሪክ ይናገራሉ', insightsEmptyDescription: 'ለማጠቃለል በቂ እንቅስቃሴ ሲኖር አዝማሚያዎችና ማሰላሰሎች ይታያሉ።',
  },
} satisfies TranslationCatalog;
