import type { TranslationCatalog } from './catalogs.ts';

export const am = {
  common: {
    back: 'ተመለስ', cancel: 'ሰርዝ', close: 'ዝጋ', continue: 'ቀጥል', create: 'ፍጠር', delete: 'አጥፋ', done: 'ተጠናቋል', edit: 'አርትዕ', goBack: 'ወደ ኋላ ተመለስ', keep: 'አቆይ', loading: 'በመጫን ላይ', noNotes: 'ማስታወሻ የለም', none: 'የለም', refresh: 'አድስ', retry: 'እንደገና ሞክር', save: 'አስቀምጥ', skip: 'ዝለል', today: 'ዛሬ', tomorrow: 'ነገ', yesterday: 'ትናንት', active: 'ንቁ', paused: 'ለጊዜው ቆሟል', archived: 'ተመዝግቧል', planned: 'የታቀደ', completed: 'ተጠናቋል', cancelled: 'ተሰርዟል', pending: 'በመጠባበቅ ላይ', inProgress: 'በሂደት ላይ', skipped: 'ተዘሏል', anyTime: 'ዛሬ በማንኛውም ጊዜ', minuteOne: '{{count}} ደቂቃ', minuteOther: '{{count}} ደቂቃዎች', hourOne: '{{count}} ሰዓት', hourOther: '{{count}} ሰዓታት',
  },
  launch: { starting: 'Planora እየተጀመረ ነው', tagline: 'ለሚያስፈልግዎ ነገር ቦታ ይስጡ።', storage: 'የአካባቢ ማከማቻ እየተዘጋጀ ነው።', account: 'መለያዎ እየተመለሰ ነው።', preferences: 'ምርጫዎችዎ እየተጫኑ ናቸው።', workspace: 'የእቅድ ቦታዎ እየተዘጋጀ ነው።' },
  tabs: { today: 'ዛሬ', planner: 'እቅድ', goals: 'ግቦች', insights: 'ግንዛቤዎች', settings: 'ቅንብሮች' },
  auth: {
    chooseTitle: 'ለዛሬ የሚስማማዎትን ይምረጡ', chooseDescription: 'Planoraን በመሣሪያዎ ብቻ ይጠቀሙ ወይም ለመገለጫና መልሶ ማግኘት መለያ ያክሉ። የእቅድ ይዘት በዚህ መሣሪያ ላይ ይቆያል።', localTitle: 'በመሣሪያው ብቻ ቀጥል', localDescription: 'መለያ አያስፈልግም። የአካባቢ የእቅድ ውሂብዎ ከመስመር ውጭ ዝግጁ ሆኖ ይቆያል።', accountTitle: 'አማራጭ መለያ', accountDescription: 'መገለጫ ይፍጠሩ ወይም ይግቡ። ይህ የአካባቢ የእቅድ መዝገቦችን አይሰቅልም፣ አያዋህድም ወይም አይተካም።', accountUnavailable: 'በዚህ ስሪት የመለያ አገልግሎቶች አልተዘጋጁም። የአካባቢ አጠቃቀም ይገኛል።', createAccount: 'መለያ ፍጠር', signIn: 'ግባ', signInTitle: 'እንኳን ደህና መጡ', signInDescription: 'ወደ አማራጭ የPlanora መለያዎ ይግቡ። የአካባቢ የእቅድ ቦታዎ ተለይቶና ዝግጁ ሆኖ ይቆያል።', createTitle: 'መለያዎን ይፍጠሩ', createDescription: 'ለመግባትና መልሶ ለማግኘት ቀላል መገለጫ ይፍጠሩ። የእቅድ ይዘት ወደ መለያ አገልግሎት አይላክም።', displayName: 'የሚታይ ስም', displayNamePlaceholder: 'እንዴት እንዲጠሩ ይፈልጋሉ', email: 'ኢሜይል', emailPlaceholder: 'you@example.com', password: 'የይለፍ ቃል', confirmPassword: 'የይለፍ ቃል ያረጋግጡ', newPassword: 'አዲስ የይለፍ ቃል', confirmNewPassword: 'አዲሱን የይለፍ ቃል ያረጋግጡ', alreadyAccount: 'መለያ አለዎት? ይግቡ', createInstead: 'መለያ ይፍጠሩ', forgotPassword: 'የይለፍ ቃል ረሱ?', recoveryEyebrow: 'መለያ መልሶ ማግኘት', recoveryTitle: 'የይለፍ ቃልዎን ይቀይሩ', recoveryDescription: 'መለያ መኖሩን ሳንገልጽ የመልሶ ማግኛ መልዕክት እንድንጠይቅ ኢሜይልዎን ያስገቡ።', sendRecovery: 'የመልሶ ማግኛ መመሪያ ላክ', secureRecovery: 'ደህንነቱ የተጠበቀ መልሶ ማግኘት', choosePassword: 'አዲስ የይለፍ ቃል ይምረጡ', choosePasswordDescription: 'ለመለያዎ አዲስ የይለፍ ቃል ይምረጡ። ይህ የአካባቢ የእቅድ ውሂብን አይቀይርም ወይም አያጠፋም።', savePassword: 'አዲስ የይለፍ ቃል አስቀምጥ', checkEmailEyebrow: 'ኢሜይልዎን ይመልከቱ', checkEmailTitle: 'አንድ ተጨማሪ እርምጃ', checkEmailDescription: 'አድራሻው የተጠየቀውን መልዕክት መቀበል ከቻለ፣ ለመቀጠል በመልዕክቱ ያለውን አገናኝ ይከተሉ።', inboxTitle: 'ቀጣዩ እርምጃ በገቢ መልዕክትዎ ውስጥ ነው', returnSignIn: 'ወደ መግቢያ ተመለስ', recoveryValidating: 'Planora የግል የክፍለ ጊዜ ዝርዝሮችን ሳያሳይ የመልሶ ማግኛ አገናኙን እያረጋገጠ ነው።', requestNewLink: 'አዲስ አገናኝ ጠይቅ', issueEyebrow: 'ሊስተካከል የሚችል ችግር', issueTitle: 'ሌላ መንገድ እንሞክር', issueDescription: 'የመለያ ጥያቄው አልተጠናቀቀም፣ ነገር ግን የአካባቢ የPlanora ውሂብዎ ደህንነቱ የተጠበቀና ዝግጁ ነው።', accountOptions: 'ወደ መለያ አማራጮች ተመለስ', profileEyebrow: 'የመለያ መገለጫ', editProfile: 'መገለጫ አርትዕ', profileDescription: 'ይህ ቀላል የመለያ መገለጫ ከአካባቢ የእቅድ መዝገቦችዎ የተለየ ነው።', profileScope: 'የመገለጫ ወሰን', saveProfile: 'መገለጫ አስቀምጥ', signOut: 'ውጣ', signOutTitle: 'ከመለያዎ ይውጡ?', signOutDescription: 'የእቅድ ውሂብዎ በዚህ መሣሪያ ላይ ይቆያል እና ከወጡ በኋላም ይገኛል።', accountLabel: 'መለያ', accountSettingsDescription: 'የመለያ ባህሪያት አማራጭ ሲሆኑ ከአካባቢ የእቅድ ውሂብ ተለይተው ይቆያሉ።', planoraAccount: 'የPlanora መለያ', localOnly: 'በመሣሪያው ብቻ', localOnlyDescription: 'ዋና የእቅድ ትሮችን ለመጠቀም መለያ አያስፈልግም።', emailVerified: 'ኢሜይል ተረጋግጧል', emailPending: 'የኢሜይል ማረጋገጫ በመጠባበቅ ላይ', viewOnboarding: 'መግቢያውን እንደገና ይመልከቱ',
    newToAccount: 'የመለያ ባህሪያትን አዲስ ነዎት?',
    passwordPrivacy: 'የይለፍ ቃልዎ በደህንነት ወደ መለያ አቅራቢው ይላካል እና በPlanora የአካባቢ የእቅድ ውሂብ ጎታ ውስጥ ፈጽሞ አይቀመጥም።',
    recoveryPrivacy: 'ለግላዊነት፣ የማረጋገጫ ገጹ ለሁሉም ትክክለኛ የኢሜይል ቅርጸቶች አንድ ነው።',
    showPassword: 'የይለፍ ቃል አሳይ', hidePassword: 'የይለፍ ቃል ደብቅ',
  },
  onboarding: {
    pageOneEyebrow: 'የተረጋጋ ጅምር', pageOneTitle: 'ለመተንፈስ ቦታ ያለው ቀንዎ', pageOneDescription: 'Planora ሌሎች የእቅድ ቦታዎችን ቅርብ አድርጎ ተግባራትንና ልማዶችን በተረጋጋ ዕለታዊ እይታ ያሰባስባል።', pageOneDetail: 'መለያ ሳይፈጥሩ ተግባራትን ያክሉ እና ልማዶችን ይመዝግቡ።', pageTwoEyebrow: 'በነባሪ አካባቢያዊ', pageTwoTitle: 'ኔትወርክ ባይኖርም ዝግጁ', pageTwoDescription: 'የእቅድ መሠረትዎ በዚህ መሣሪያ ላይ ይቀመጣል እና ከመስመር ውጭ ይገኛል። የአካባቢ እርምጃዎች የመለያ አገልግሎት አይጠብቁም።', pageTwoDetail: 'የአካባቢ ውሂብ ከዳግም ማስነሳት በኋላ ይቆያል እና ከመለያ ክፍለ ጊዜ የተለየ ነው።', pageThreeEyebrow: 'ምርጫው የእርስዎ ነው', pageThreeTitle: 'መለያ አማራጭ ነው', pageThreeDescription: 'ለመገለጫና መልሶ ማግኘት መለያ ይፍጠሩ ወይም በመሣሪያው ብቻ ይቀጥሉ። የእቅድ ይዘት አይሰቀልም ወይም አይመሳሰልም።', pageThreeDetail: 'የአካባቢ መለያዎችን ሳይቀይሩ በኋላ ከቅንብሮች መግባት ይችላሉ።', close: 'መግቢያውን ዝጋ', skip: 'መግቢያውን ዝለል', step: 'ደረጃ {{current}} ከ{{total}}', stepAnnouncement: 'ደረጃ {{current}} ከ{{total}}። {{title}}', startLocally: 'በመሣሪያው ጀምር',
  },
  today: {
    greeting: 'የዛሬ ግልጽ እይታ', subtitle: 'የሚያስፈልግዎትን ይምረጡ፣ ከዚያ ለቀኑ ለውጥ ቦታ ይተዉ።', quickPlaceholder: 'ለዛሬ ተግባር ያክሉ', quickLabel: 'ተግባር በፍጥነት ያክሉ', quickHint: 'ዛሬ የሚደርስ ተግባር ይፈጥራል', add: 'ጨምር', progress: '{{completed}} ከ{{total}} ተጠናቋል', workload: '{{planned}} ታቅዷል · {{remaining}} ቀርቷል', nextUp: 'ቀጣይ', priority: 'ቅድሚያ እና ያለፈባቸው', remaining: 'የዛሬ ተግባራት', routines: 'የታቀዱ ልማዶች', agenda: 'የቀን መርሐግብር ቅድመ እይታ', completed: 'የተጠናቀቀ', showCompleted: 'የተጠናቀቁትን አሳይ', hideCompleted: 'የተጠናቀቁትን ደብቅ', quietEmpty: 'አሁን ትኩረትዎን የሚፈልግ ነገር የለም።', noPriority: 'ቅድሚያ ያለው ወይም ጊዜው ያለፈ ተግባር የለም።', noRemaining: 'ለዛሬ የቀረ ተግባር የለም።', noRoutines: 'ዛሬ የታቀደ ልማድ የለም።', noAgenda: 'እስካሁን የታቀደ የጊዜ ክፍል የለም።', allTasks: 'ሁሉም ተግባራት', allRoutines: 'ልማዶች', openPlanner: 'እቅድ ክፈት', moreActions: 'ተጨማሪ እርምጃዎች', loading: 'ቀንዎ እየተጫነ ነው።', refreshTitle: 'ቀንዎ መታደስ አለበት', failed: 'ቀንዎን መጫን አልተቻለም።', completedToday: 'ዛሬ ተጠናቋል', skippedToday: 'ዛሬ ተዘሏል', markComplete: 'እንደተጠናቀቀ ምልክት አድርግ', markSkipped: 'እንደተዘለለ ምልክት አድርግ', undo: 'መዝገቡን ቀልብስ', overdue: 'ጊዜው ያለፈ', dueToday: 'ዛሬ የሚደርስ', unscheduled: 'ገቢ ሳጥን',
  },
  tasks: {
    title: 'ሁሉም ተግባራት', new: 'አዲስ ተግባር', details: 'የተግባር ዝርዝር', createDescription: 'የሚያስፈልግዎትን ያክሉ፣ ጊዜውን መወሰን ካገዘ ብቻ ይቀይሩ።', editDescription: 'የአካባቢ መለያውን ሳይቀይሩ ተግባሩን ያዘምኑ።', loading: 'የተግባር ዝርዝር እየተጫነ ነው።', refreshTitle: 'የተግባር ዝርዝር መታደስ አለበት', listRefresh: 'የተግባር ዝርዝርዎ መታደስ አለበት', notLoaded: 'ተግባሩን መጫን አልተቻለም።', unavailable: 'ተግባሩ አይገኝም', unavailableDescription: 'ተወግዶ ወይም ተቀይሮ ሊሆን ይችላል። ወደ ዛሬ ተመልሰው ያድሱ።', emptyTitle: 'እስካሁን ተግባር የለም', emptyDescription: 'ፈጣን ግቤቶችና ሙሉ ተግባራት እዚህ ይገኛሉ።', createAction: 'ተግባር ፍጠር', actions: 'የተግባር እርምጃዎች', complete: 'ተግባር አጠናቅ', reopen: 'ተግባር እንደገና ክፈት', cancel: 'ተግባር ሰርዝ', delete: 'ተግባር አጥፋ', cancelTitle: 'ተግባሩ ይሰረዝ?', cancelDescription: 'ተግባሩ ከንቁ የቀን ክፍሎች ይወጣል እና በኋላ እንደገና ሊከፈት ይችላል።', keep: 'ተግባሩን አቆይ', deleteTitle: 'ተግባሩ ይጥፋ?', deleteDescription: 'ይህ ተግባሩን ከዕለታዊ እይታዎች ያስወግዳል። እዚህ ይህን መቀልበስ አይቻልም።', overdue: 'ጊዜው ያለፈ', upcoming: 'መጪ', unscheduled: 'ያልታቀደ', opensDetails: 'የተግባር ዝርዝርን ይከፍታል', titleField: 'ርዕስ', notesField: 'ማስታወሻዎች', priorityField: 'ቅድሚያ', statusField: 'ሁኔታ', dueDate: 'የመድረሻ ቀን', dueDateHint: 'YYYY-MM-DD ይጠቀሙ ወይም ባዶ ይተዉ።', scheduledTime: 'የታቀደ ጊዜ', timeHint: 'የ24 ሰዓት HH:MM ቅርጸት ይጠቀሙ ወይም ባዶ ይተዉ።', priorityNone: 'ቅድሚያ የለም', priorityLow: 'ዝቅተኛ ቅድሚያ', priorityMedium: 'መካከለኛ ቅድሚያ', priorityHigh: 'ከፍተኛ ቅድሚያ',
  },
  routines: {
    title: 'ልማዶች', new: 'አዲስ ልማድ', details: 'የልማድ ዝርዝር', description: 'ያለ ማስታወሻ ወይም ውጤት ቀላል ዕለታዊ ወይም ሳምንታዊ ልማድ ይገንቡ።', loading: 'የልማድ ዝርዝር እየተጫነ ነው።', refreshTitle: 'የልማድ ዝርዝር መታደስ አለበት', listRefresh: 'የልማድ ዝርዝርዎ መታደስ አለበት', notLoaded: 'ልማዱን መጫን አልተቻለም።', unavailable: 'ልማዱ አይገኝም', unavailableDescription: 'ወደ ዛሬ ተመልሰው የአካባቢ የእቅድ ውሂብዎን ያድሱ።', emptyTitle: 'እስካሁን ልማድ የለም', emptyDescription: 'ዕለታዊ ልማድ ይፍጠሩ ወይም የሚስማሙትን የሳምንት ቀናት ይምረጡ።', createAction: 'ልማድ ፍጠር', opensDetails: 'የልማድ ዝርዝርን ይከፍታል', schedule: 'መርሐግብር', everyDay: 'በየቀኑ', selectedDays: 'የተመረጡ ቀናት', weekdays: 'የሳምንት ቀናት', preferredTime: 'የተመረጠ ጊዜ', state: 'የልማድ ሁኔታ',
  },
  planner: {
    title: 'እቅድ', day: 'ቀን', week: 'ሳምንት', previousDay: 'ያለፈው ቀን', nextDay: 'ቀጣዩ ቀን', previousWeek: 'ያለፈው ሳምንት', nextWeek: 'ቀጣዩ ሳምንት', currentWeek: 'የአሁኑ ሳምንት', date: 'ቀን', timeline: 'ዕለታዊ የጊዜ መስመር', newBlock: 'አዲስ የጊዜ ክፍል', editBlock: 'የጊዜ ክፍል አርትዕ', blockDetails: 'የጊዜ ክፍል ዝርዝር', unscheduledTasks: 'ያልታቀዱ ተግባራት', scheduleTask: 'ተግባር አቅድ', noBlocks: 'ለዚህ ቀን የታቀደ የጊዜ ክፍል የለም።', noTasks: 'ሁሉም ሊሠሩ የሚችሉ ተግባራት የጊዜ ክፍል አላቸው።', workload: 'የሥራ ጫና', plannedMinutes: '{{duration}} ታቅዷል', remainingCapacity: '{{duration}} ቀርቷል', overCapacity: '{{duration}} ከዕለታዊ አቅምዎ በላይ', withinCapacity: 'በዕለታዊ አቅምዎ ውስጥ', overlapOne: '{{count}} መደራረብ', overlapOther: '{{count}} መደራረቦች', unscheduledOne: '{{count}} ያልታቀደ ተግባር', unscheduledOther: '{{count}} ያልታቀዱ ተግባራት', blockOne: '{{count}} ክፍል', blockOther: '{{count}} ክፍሎች', taskOne: '{{count}} ተግባር', taskOther: '{{count}} ተግባራት', overlapWarning: 'ይህ ክፍል ከሌላ ክፍል ጋር ይደራረባል። ማቆየት ወይም ጊዜውን መቀየር ይችላሉ።', overlapCounted: 'የተደራረቡ ክፍሎች በታቀደው ጊዜ ውስጥ ለየብቻ ይቆጠራሉ።', overloaded: 'ከአቅም በላይ', linkedTask: 'የተያያዘ ተግባር', linkedRoutine: 'የተያያዘ ልማድ', removeLink: 'ግንኙነት አስወግድ', completeBlock: 'ክፍሉን አጠናቅ', reopenBlock: 'ክፍሉን እንደገና ክፈት', cancelBlock: 'ክፍሉን ሰርዝ', deleteBlock: 'ክፍሉን አጥፋ', deleteTitle: 'የጊዜ ክፍሉ ይጥፋ?', deleteDescription: 'ይህ የታቀደውን የጊዜ ክፍል ብቻ ያስወግዳል። የተያያዙ ተግባራትና ልማዶች ይቆያሉ።', cancelTitle: 'የጊዜ ክፍሉ ይሰረዝ?', cancelDescription: 'የተሰረዙ ክፍሎች በታሪክ ውስጥ ይቆያሉ እና በአቅም ውስጥ አይቆጠሩም።', keepBlock: 'ክፍሉን አቆይ', startTime: 'የመጀመሪያ ጊዜ', endTime: 'የመጨረሻ ጊዜ', titleField: 'ርዕስ', notesField: 'ማስታወሻዎች', statusField: 'ሁኔታ', repeat: 'ድግግሞሽ', repeatNone: 'አይደገምም', repeatDaily: 'በየቀኑ', repeatWeekly: 'በየሳምንቱ', repeatInterval: 'የድግግሞሽ ርቀት', repeatEnd: 'ድግግሞሽ የሚያበቃበት ቀን', editOccurrence: 'ይህን ጊዜ አርትዕ', editFuture: 'ይህንና የወደፊት ጊዜያትን አርትዕ', recurrenceBounded: 'ድግግሞሾች በሚንቀሳቀስ የስምንት ሳምንት መስኮት ይዘጋጃሉ።', move: 'አንቀሳቅስ ወይም እንደገና አቅድ', selectedDay: 'የተመረጠ ቀን', currentTime: 'የአሁኑ ጊዜ', capacitySummary: '{{planned}} ታቅዷል፣ አቅም {{capacity}}', loading: 'መርሐግብርዎ እየተጫነ ነው።', refreshTitle: 'መርሐግብርዎ መታደስ አለበት',
  },
  goals: {
    heading: 'ግቦች', summaryActive: '{{count}} ንቁ', create: 'ግብ ፍጠር', edit: 'ግብ አርትዕ', details: 'የግብ ዝርዝር', formDescription: 'ወደ ውጤት ሰሌዳ ሳይቀየር ግልጽ አቅጣጫ ይቅረጹ።',
    titleField: 'ርዕስ', descriptionField: 'መግለጫ', motivationField: 'ይህ ለምን እንደሚያስፈልግ', area: 'አካባቢ', horizon: 'የጊዜ ክልል', horizonMonth: 'ወር', horizonQuarter: 'ሩብ ዓመት', horizonYear: 'ዓመት', horizonSomeday: 'አንድ ቀን', targetDate: 'የታለመ ቀን', targetDateHint: 'YYYY-MM-DD ይጠቀሙ ወይም ባዶ ይተዉት።',
    status: 'ሁኔታ', statusActive: 'ንቁ', statusPaused: 'ለጊዜው የቆመ', statusCompleted: 'የተጠናቀቀ', statusAbandoned: 'የተተወ', progressMethod: 'የእድገት ዘዴ', progressMilestones: 'ደረጃዎች', progressTasks: 'የተገናኙ ተግባራት', progressManual: 'በእጅ መቶኛ', progressNone: 'ቁጥራዊ እድገት የለም', manualProgress: 'በእጅ የሚገባ እድገት', manualHint: 'ከ0 እስከ 100 ያለ ሙሉ መቶኛ ያስገቡ።',
    loading: 'ግቦች በመጫን ላይ።', refreshTitle: 'ግቦች መታደስ ያስፈልጋቸዋል', notLoaded: 'ግቦችን መጫን አልተቻለም። የተቀመጠው ውሂብ አልተቀየረም።', unavailable: 'ግቡ አይገኝም', unavailableDescription: 'ተወግዶ ወይም ተቀይሮ ሊሆን ይችላል። ወደ ግቦች ይመለሱና ያድሱ።', emptyTitle: 'ትርጉም ላለው አቅጣጫ ቦታ ይስጡ', emptyDescription: 'ረጅም መንገድ ከቀጣይ ረጋ ያለ እርምጃ ሲጠቀም ግብ ይፍጠሩ።',
    search: 'ግቦችን ፈልግ', noMatches: 'ከዚህ ፍለጋ ወይም ማጣሪያ ጋር የሚዛመድ ግብ የለም።', filterCurrent: 'ወቅታዊ', filterCompleted: 'የተጠናቀቁ', filterAll: 'ሁሉም', activeGoals: 'ንቁ ግቦች', pausedGoals: 'ለጊዜው የቆሙ ግቦች', completedGoals: 'የተጠናቀቁ ግቦች', somedayGoals: 'የአንድ ቀን ግቦች', abandonedGoals: 'የተተዉ ግቦች', noTargetDate: 'የታለመ ቀን የለም', targetContext: 'ዒላማ {{date}}',
    nextMilestone: 'ቀጣይ ደረጃ', nextAction: 'ቀጣይ ተግባር', notStarted: 'አልተጀመረም', progressCount: '{{completed}} ከ{{total}} ተጠናቋል', percentComplete: '{{percent}} ተጠናቋል', noNumericProgress: 'እድገቱ ቀጣዩን ጠቃሚ እርምጃ ይከተላል።', opensDetails: 'የግብ ዝርዝርን ይከፍታል', motivation: 'ለምን እንደሚያስፈልግ',
    milestones: 'ደረጃዎች', linkedTasks: 'የተገናኙ ቀጣይ ተግባራት', supportingRoutines: 'ደጋፊ ልማዶች', addMilestone: 'ደረጃ ጨምር', linkTask: 'ተግባር አገናኝ', linkRoutine: 'ልማድ አገናኝ', createTask: 'ለግቡ ተግባር ፍጠር', noMilestones: 'እስካሁን ደረጃ የለም።', noTasks: 'የተገናኘ ተግባር የለም።', noRoutines: 'እስካሁን ደጋፊ ልማድ የለም።',
    milestoneTitle: 'የደረጃ ርዕስ', milestoneNotes: 'ማስታወሻዎች', milestoneDate: 'የታለመ ቀን', milestonePending: 'በመጠባበቅ ላይ', milestoneCompleted: 'የተጠናቀቀ', milestoneCancelled: 'የተሰረዘ', newMilestone: 'አዲስ ደረጃ', editMilestone: 'ደረጃ አርትዕ', completeMilestone: 'ደረጃ አጠናቅቅ', reopenMilestone: 'ደረጃ እንደገና ክፈት', cancelMilestone: 'ደረጃ ሰርዝ', deleteMilestone: 'ደረጃ አጥፋ', moveUp: 'ወደ ላይ አንቀሳቅስ', moveDown: 'ወደ ታች አንቀሳቅስ', moveUpHint: 'ይህን ደረጃ በግቡ ውስጥ ቀደም ያደርገዋል።', moveDownHint: 'ይህን ደረጃ በግቡ ውስጥ ዘግይቶ ያደርገዋል።',
    setNextAction: 'እንደ ቀጣይ ተግባር አዘጋጅ', clearNextAction: 'ቀጣይ ተግባርን አጽዳ', unlinkTask: 'ተግባርን ለይ', unlinkRoutine: 'ልማድን ለይ', routineCompletedToday: 'ዛሬ ተጠናቋል', routineSkippedToday: 'ዛሬ ታልፏል', routinePendingToday: 'ዛሬ በመጠባበቅ ላይ',
    actions: 'የግብ ተግባራት', pause: 'ግብን ለጊዜው አቁም', resume: 'ግብን ቀጥል', complete: 'ግብን አጠናቅቅ', reopen: 'ግብን እንደገና ክፈት', abandon: 'ግብን ተው', delete: 'ግብን አጥፋ', pauseTitle: 'ይህን ግብ ለጊዜው ማቆም?', pauseDescription: 'ግቡ እንደ ንቁ ሳይታይ ይገኛል።', completeTitle: 'ይህን ግብ ማጠናቀቅ?', completeDescription: 'ይህ የተገናኙ ተግባራትን ወይም ልማዶችን ሳይቀይር ማጠናቀቁን ይመዘግባል።', abandonTitle: 'ይህን ግብ መተው?', abandonDescription: 'ግቡ ከወቅታዊ ክፍሎች ይወጣል፣ ተያያዥ መዝገቦቹ ግን ይጠበቃሉ።', deleteTitle: 'ይህን ግብ ማጥፋት?', deleteDescription: 'ግቡ ከማያዎች ይወጣል። የተገናኙ ተግባራትና ልማዶች ይቀራሉ።',
    deleteMilestoneTitle: 'ይህን ደረጃ ማጥፋት?', deleteMilestoneDescription: 'ይህ ደረጃውን ከግቡ ያስወግዳል። ሌሎች መዝገቦች ይቀራሉ።', keepGoal: 'ግብን አቆይ', keepMilestone: 'ደረጃውን አቆይ', chooseTask: 'ተግባር ምረጥ', chooseRoutine: 'ልማድ ምረጥ', availableTasks: 'ያሉ ተፈጻሚ ተግባራት', availableRoutines: 'ያሉ ንቁ ልማዶች', noAvailableTasks: 'ያልተገናኘ ተፈጻሚ ተግባር የለም።', noAvailableRoutines: 'ያልተገናኘ ንቁ ልማድ የለም።', completionSuggestion: 'ሁሉም ደረጃዎች ተጠናቀዋል። ግቡ እንደተጠናቀቀ ሲሰማዎት ያጠናቅቁት።', needsAttention: 'ትኩረት ያስፈልገዋል', linkedGoal: 'ግብ፦ {{title}}', openGoal: 'ግብ {{title}} ክፈት',
  },
  insights: {
    heading: 'ግንዛቤዎች', description: 'የአካባቢ የእቅድ እንቅስቃሴዎን በረጋ እና በእውነታ ማጠቃለያዎች ይረዱ።', destination: 'የግንዛቤ ክፍል', summary: 'ማጠቃለያ', trends: 'አዝማሚያዎች', reflections: 'ነጸብራቆች', range: 'የጊዜ ክልል', last7Days: 'ያለፉት 7 ቀናት', last4Weeks: 'ያለፉት 4 ሳምንታት', last12Weeks: 'ያለፉት 12 ሳምንታት', periodDates: 'ከ{{start}} እስከ {{end}}', partialPeriod: 'የአሁኑ ጊዜ ዛሬን ያካትታል እና ሊቀየር ይችላል። የንጽጽር ጊዜው ተመሳሳይ የቀን ብዛት አለው።', loading: 'የአካባቢ ግንዛቤዎች እየተጫኑ ነው።', refreshTitle: 'ግንዛቤዎች መታደስ ያስፈልጋቸዋል', partialData: 'የቅርብ ጊዜው ማደስ አልተጠናቀቀም። እነዚህ በአካባቢው የተጫኑ የመጨረሻ ውጤቶች ናቸው።', localPrivacy: 'በንቁው የሥራ ቦታ መረጃ በዚህ መሣሪያ ላይ ይሰላል። የእቅድ ወይም የነጸብራቅ መረጃ ለትንታኔ አይላክም።', noActivityTitle: 'ገና በቂ እንቅስቃሴ የለም', noActivity: 'በዚህ ጊዜ የተመዘገበ እንቅስቃሴ የለም። የአሁኑ የተግባር እና የግብ አውድ ይገኛል።',
    tasksCompleted: 'የተጠናቀቁ ተግባራት', tasksCompletedBasis: 'በተመረጠው ጊዜ ውስጥ የማጠናቀቂያ ጊዜ ያላቸው ተግባራት።', actionableRemaining: 'የቀሩ ሊሠሩ የሚችሉ ተግባራት', actionableRemainingBasis: 'በዚህ የሥራ ቦታ ውስጥ ያሉ የአሁኑ በመጠባበቅ ላይ እና በሂደት ላይ ያሉ ተግባራት።', completionRatio: 'የተግባር ማጠናቀቂያ ጥምርታ', completionRatioBasis: 'በጊዜው የተጠናቀቁ በእነዚያ እና በጊዜው የሚደርሱ የአሁኑ ተግባራት ድምር ይካፈላሉ።', plannedTime: 'የታቀደ ጊዜ', plannedTimeBasis: 'በተመረጠው ጊዜ ውስጥ ያልተሰረዙ የእቅድ ክፍሎች ቆይታ።', completedBlockTime: 'የተጠናቀቁ ክፍሎች ጊዜ', completedBlockTimeBasis: 'በጊዜው ተጠናቋል ተብለው የተመዘገቡ ክፍሎች ቆይታ።', overCapacityDays: 'ከአቅም በላይ የሆኑ ቀናት', overCapacityBasis: 'የታቀዱ ደቂቃዎች ከተዋቀረው ዕለታዊ አቅም የሚበልጡባቸው ቀናት።', overlaps: 'የተደራረቡ ክፍል ጥንዶች', overlapBasis: 'የአካባቢ ሰዓታቸው የሚደራረብ ያልተሰረዙ ክፍሎች ጥንዶች።', routineOutcomes: 'የተጠናቀቁ / የታለፉ / በመጠባበቅ ላይ ያሉ ልማዶች', routineOutcomesBasis: 'ከአሁኑ ንቁ የልማድ መርሐግብሮች የተገኙ ውጤቶችና ክፍት አጋጣሚዎች።', milestonesCompleted: 'የተጠናቀቁ ደረጃዎች', milestonesBasis: 'በጊዜው ውስጥ የማጠናቀቂያ ጊዜ ያላቸው ደረጃዎች።', activeGoals: 'ንቁ ግቦች', activeGoalsBasis: 'ያልተሰረዙ እና ንቁ ተብለው የተመዘገቡ የአሁኑ ግቦች።', reflectionCount: 'ነጸብራቆች', reflectionCountBasis: 'ጊዜያቸው በዚህ ክልል የሚጀምር ዕለታዊ፣ ሳምንታዊ እና የግብ ነጸብራቆች።',
    explanations: 'መዝገቦቹ የሚያሳዩት', explanationBasis: 'ከላይ ባሉት መለኪያዎች የተገኙ በደንብ የተደረደሩ እና እስከ አራት የተገደቡ መግለጫዎች።', explainOverCapacity: 'በ{{count}} ቀናት ከመረጡት አቅም በላይ ጊዜ አቅደዋል።', explainOverlap: 'በዚህ ጊዜ {{count}} የተደራረቡ የጊዜ ሰሌዳ ጥንዶች አሉ።', explainHighPriority: '{{count}} ከፍተኛ ቅድሚያ ያላቸው ተግባራት ቀርተዋል።', explainRoutineMore: 'የልማድ ምዝገባዎች ከቀደመው ጊዜ በለጡ።', explainRoutineSimilar: 'የልማድ ምዝገባዎች ከቀደመው ጊዜ ጋር ተመሳሳይ ነበሩ።', explainRoutineLess: 'የልማድ ምዝገባዎች ከቀደመው ጊዜ ያነሱ ነበሩ።', explainInsufficient: 'የንጽጽር አዝማሚያ ለመግለጽ ገና በቂ የተመዘገበ እንቅስቃሴ የለም።',
    workload: 'የሥራ ጫና ምልክቶች', blockCompletion: 'ከ{{total}} የታቀዱ ክፍሎች {{completed}} ተጠናቀዋል።', unscheduledTasksValue: '{{count}} ሊሠሩ የሚችሉ ተግባራት ያልተሰረዘ የእቅድ ክፍል የላቸውም።', overlapCounting: 'የተደራረቡ ክፍሎች ቆይታ በታቀደው ጊዜ ውስጥ ለየብቻ ይቆጠራል።', dayWorkload: 'በዚህ ጊዜ የታቀደ ጊዜ ያላቸው ቀናት', dayWorkloadValue: '{{planned}} ታቅዷል፤ አቅም {{capacity}}።', noPlannedTime: 'በዚህ ጊዜ የተመዘገበ የታቀደ ጊዜ የለም።', weekdayDistribution: 'በሳምንቱ ቀን የሥራ ጫና ስርጭት', taskPatterns: 'የተግባር ማጠቃለያዎች', overdueValue: '{{count}} ሊሠሩ የሚችሉ ተግባራት ጊዜ አልፎባቸዋል።', pendingValue: '{{count}} ተግባራት በመጠባበቅ ላይ ናቸው።', inProgressValue: '{{count}} ተግባራት በሂደት ላይ ናቸው።', activeGoalTasksValue: '{{count}} ሊሠሩ የሚችሉ ተግባራት ከንቁ ግቦች ጋር ተገናኝተዋል።', completedByPriority: 'በቅድሚያ የተጠናቀቁ ተግባራት', completedByDay: 'በቀን የተጠናቀቁ ተግባራት', completedDayValue: '{{count}} ተግባራት ተጠናቀዋል።', noCompletedTasks: 'በዚህ ጊዜ ውስጥ የተግባር ማጠናቀቂያ ጊዜ የለም።',
    routineSummary: 'የልማድ ማጠቃለያ', routineCompletedValue: '{{count}} የተጠናቀቁ ምዝገባዎች።', routineSkippedValue: '{{count}} የታለፉ ምዝገባዎች።', routinePendingValue: '{{count}} የታቀዱ አጋጣሚዎች ምዝገባ የላቸውም።', routineOpportunityValue: '{{count}} ከአሁኑ ንቁ መርሐግብሮች የታቀዱ አጋጣሚዎች።', routineCompletionRatio: 'የማጠናቀቂያ ጥምርታ፦ {{completed}}/{{scheduled}} የታቀዱ አጋጣሚዎች።', routineBasis: 'የአሁኑ መርሐግብሮች ለሁለቱም ጊዜያት በተመሳሳይ ይተገበራሉ። የቀድሞ ለውጦች አይገመቱም።', routineItemValue: '{{completed}} ተጠናቋል፣ {{skipped}} ታልፏል፣ {{pending}} በመጠባበቅ ላይ፣ {{scheduled}} ታቅዷል።', goalContext: 'የግብ አውድ', linkedTasksCompletedValue: 'በዚህ ጊዜ {{count}} ከግብ ጋር የተገናኙ ተግባራት ተጠናቀዋል።', upcomingTargetsValue: '{{count}} ንቁ ግቦች በዚህ ክልል ርዝመት ውስጥ የሚደርስ ቀን አላቸው።', noNextActionValue: '{{count}} ንቁ ግቦች የተመረጠ ሊሠራ የሚችል ቀጣይ ተግባር የላቸውም።', goalReflectionsValue: '{{count}} የግብ ነጸብራቆች በዚህ ጊዜ ይጀምራሉ።', goalProgressBasis: 'የግብ እድገት በእያንዳንዱ ግብ ላይ የተመረጠውን ዘዴ ይጠቀማል።',
    trendBasis: 'እያንዳንዱ ዋጋ ተመሳሳይ የቀን ብዛት ካለው ቀደምት ጊዜ ጋር ይነጻጸራል። አዝማሚያ ቢያንስ ሁለት ምዝገባዎችን ይፈልጋል።', directionMore: 'ከቀደመው ጊዜ የበለጠ', directionSimilar: 'ከቀደመው ጊዜ ጋር ተመሳሳይ', directionLess: 'ከቀደመው ጊዜ ያነሰ', directionInsufficient: 'ለማነጻጸር በቂ ውሂብ የለም', exactComparison: 'የአሁኑ፦ {{current}}። የቀደመው፦ {{previous}}።', absoluteDifference: 'ፍጹም ልዩነት፦ {{difference}}።', percentageDifference: 'ከቀደመው ዋጋ አንጻር {{percentage}}።', minimumSample: 'ቢያንስ {{count}} የተመዘገቡ ምልከታዎች ያስፈልጋሉ።', trendTasks: 'የተጠናቀቁ ተግባራት', trendPlanned: 'የታቀደ የሥራ ጫና', trendCapacity: 'ከአቅም በላይ የሆኑ ቀናት', trendRoutines: 'የልማድ ምዝገባዎች', trendMilestones: 'የተጠናቀቁ ደረጃዎች', trendReflections: 'የነጸብራቅ እንቅስቃሴ',
  },
  reflections: {
    create: 'ነጸብራቅ ፍጠር', edit: 'ነጸብራቅ አርትዕ', daily: 'ዕለታዊ ነጸብራቅ', weekly: 'ሳምንታዊ ነጸብራቅ', goal: 'የግብ ነጸብራቅ', newDaily: 'ስለ ዛሬ ያስቡ', newWeekly: 'ስለዚህ ሳምንት ያስቡ', reflectToday: 'ስለ ዛሬ ያስቡ', reflectGoal: 'ስለዚህ ግብ ያስቡ', history: 'የነጸብራቅ ታሪክ', emptyTitle: 'ገና ነጸብራቅ የለም', empty: 'ዕለታዊ፣ ሳምንታዊ እና የግብ ነጸብራቆች እዚህ ይቆያሉ።', optionalQuestions: 'አማራጭ ጥያቄዎች', questionImportant: 'ዛሬ አስፈላጊ የሆነው ምን ነበር?', questionHelped: 'እቅድዎን የረዳው ምንድን ነው?', questionAdjust: 'ምን ማስተካከል ይፈልጋሉ?', questionNextWeek: 'በሚቀጥለው ሳምንት ትኩረት የሚገባው ምንድን ነው?', questionGoalProgress: 'ለዚህ ግብ ዋጋ ያለው እድገት ምንድን ነው?', questionGoalNext: 'ጠቃሚ ቀጣይ እርምጃ ምን ይሆናል?', body: 'ነጸብራቅ', bodyHint: 'ያስፈልጋል። የመጀመሪያና የመጨረሻ ክፍተቶች ይወገዳሉ። {{count}} ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', mood: 'አማራጭ ስሜት', moodLow: 'ዝቅተኛ', moodSteady: 'የተረጋጋ', moodGood: 'ጥሩ', moodGreat: 'በጣም ጥሩ', moodValue: 'ስሜት፦ {{mood}}', moodLimit: 'ስሜት አማራጭ መለያ ብቻ ነው። አይገመትም ወይም ወደ ውጤት አይቀየርም።', delete: 'ነጸብራቅ አጥፋ', deleteTitle: 'ይህን ነጸብራቅ ማጥፋት?', deleteDescription: 'ነጸብራቁ ከታሪክ ይወጣል። ሌሎች የእቅድ መዝገቦች አይቀየሩም።', unavailable: 'ነጸብራቁ አይገኝም', unavailableDescription: 'ተወግዶ ወይም ተቀይሮ ሊሆን ይችላል። ወደ ግንዛቤዎች ይመለሱና ያድሱ።',
  },
  reminders: {
    title: 'ማስታወሻ', manage: 'ማስታወሻ አስተዳድር', unavailable: 'ማስታወሻው አይገኝም', unavailableDescription: 'ይህ የእቅድ ንጥል ጠፍቷል፣ ተወግዷል ወይም ከንቁ የሥራ ቦታ ውጭ ነው።', permissionExplanation: 'ማስታወሻዎች በዚህ መሣሪያ ላይ ይቆያሉ። ፈቃድ የሚጠየቀው ማስታወሻን ለመፍቀድ ሲመርጡ ብቻ ነው።', permissionStatus: 'የማሳወቂያ ፈቃድ', permissionUndetermined: 'አልተጠየቀም', permissionAllowed: 'ተፈቅዷል', permissionDenied: 'ለአሁን ተከልክሏል', permissionBlocked: 'በመሣሪያ ቅንብሮች ታግዷል', permissionUnavailable: 'በዚህ መድረክ አይገኝም', allow: 'ማስታወሻዎችን ፍቀድ', openSettings: 'የመሣሪያ ቅንብሮችን ክፈት', enabled: 'ማስታወሻ ንቁ ነው', deliveryNote: 'የማድረሻ ጊዜን ስርዓተ ክወናው ይቆጣጠራል፤ ትክክለኛ ሰዓት አይታሰብም።', timing: 'የማስታወሻ ጊዜ', relative: 'ከታቀደው ጊዜ በፊት', absolute: 'የተወሰነ ቀንና ሰዓት', offset: 'ምን ያህል ቀደም', atTime: 'በጊዜው', before15: 'ከ15 ደቂቃ በፊት', before60: 'ከ1 ሰዓት በፊት', beforeDay: 'ከ1 ቀን በፊት', date: 'የማስታወሻ ቀን', time: 'የማስታወሻ ሰዓት', upcoming: 'የሚመጣ ማስታወሻ ሁኔታ', reasonQuiet_hours_stale: 'የጸጥታ ሰዓት ማዘግየት በጣም ዘግይቶ ስለሚሆን ተዘሏል።', reasonSchedule_failed: 'መርሐግብሩ ሌላ ሙከራ ይፈልጋል።', reasonCancel_failed: 'የቀድሞ የመሣሪያ መርሐግብር ገና መወገድ አልቻለም።', genericTitle: 'የPlanora ማስታወሻ', genericBody: 'ያቀዱትን ለመመልከት Planoraን ይክፈቱ።', fallbackTitle: 'ይህ ማስታወሻ ንጥሉን መክፈት አይችልም', fallbackMissing: 'ንጥሉ ተወግዶ ወይም የሌላ የሥራ ቦታ ሊሆን ይችላል። የአካባቢ ውሂብዎ አልተቀየረም።', fallbackMalformed: 'የማስታወሻው መድረሻ ትክክል አልነበረም። Planora ይህን ደህነቱ የተጠበቀ ገጽ ከፈተ።', settingsTitle: 'ማስታወሻዎችና የጸጥታ ሰዓት', showTitles: 'የእቅድ ርዕሶችን በማሳወቂያዎች አሳይ', showTitlesDescription: 'በነባሪ ጠፍቷል። አጠቃላይ ጽሑፍ የመቆለፊያ ማያ ዝርዝሮችን ይጠብቃል።', quietHours: 'የጸጥታ ሰዓት ተጠቀም', quietHoursDescription: 'በጸጥታ ሰዓት ያሉ ማስታወሻዎች አሁንም ጠቃሚ ከሆኑ ወደ መጨረሻው ይሄዳሉ፤ ያለፉት ይዘለላሉ።', quietStart: 'የጸጥታ ሰዓት መጀመሪያ', quietEnd: 'የጸጥታ ሰዓት መጨረሻ', settingsSaved: 'የማስታወሻ ምርጫዎች በአካባቢው ተቀምጠዋል።', reconcile: 'የመሣሪያ መርሐግብሮችን አስታርቅ', reconcileResult: '{{scheduled}} ታቅደዋል፣ {{skipped}} ተዘለዋል፣ {{errors}} ትኩረት ይፈልጋሉ።',
    permissionDevelopmentBuildRequired: 'ማስታወሻዎች Expo Go ውጭ የልማት ግንባታ ያስፈልጋቸዋል።',
  },
  calendar: {
    title: 'የመሣሪያ ቀን መቁጠሪያ', explanation: 'የPlanora የጊዜ ክፍሎችን ወደ ሊጻፍበት የሚችል የመሣሪያ ቀን መቁጠሪያ በአንድ አቅጣጫ ይላኩ። Planora ያልተዛመዱ ክስተቶችን አያስገባም።', mobileOnly: 'የመሣሪያ ቀን መቁጠሪያ ማስወጣት በAndroid እና iOS ይገኛል። የPlanora እቅድዎ በድር ላይ ይገኛል።', choose: 'ሊጻፍበት የሚችል ቀን መቁጠሪያ ምረጥ', selected: 'የተመረጠ ቀን መቁጠሪያ፦ {{name}}', noneSelected: 'መድረሻ ቀን መቁጠሪያ አልተመረጠም', noWritable: 'ሊጻፍባቸው የሚችሉ ቀን መቁጠሪያዎች የሉም።', disconnect: 'የተመረጠውን ቀን መቁጠሪያ ርሳ', exportTitle: 'ወደ መሣሪያ ቀን መቁጠሪያ ላክ', exportDescription: 'ይህ የጊዜ ክፍል ብቻ ይላካል። ውጫዊ ለውጦች ያለ ውሳኔዎ አይተኩም።', chooseInSettings: 'ከማስወጣትዎ በፊት በቅንብሮች ውስጥ ቀን መቁጠሪያ ይምረጡ።', export: 'የጊዜ ክፍሉን ላክ', updateExport: 'ማስወጣቱን ፈትሽና አዘምን', removeExport: 'የቀን መቁጠሪያ ግንኙነትን አስወግድ', removeTitle: 'ይህን የቀን መቁጠሪያ ማስወጣት ያስወግዱ?', removeDescription: 'የመሣሪያውን ክስተት ለማቆየት ወይም ክስተቱንና የPlanora ግንኙነትን ሁለቱንም ለማስወገድ ይምረጡ።', keepExternal: 'የቀን መቁጠሪያ ክስተትን አቆይ', removeBoth: 'ሁለቱንም አስወግድ', missingConflict: 'የተገናኘው ክስተት አልተገኘም። አዲስ ክስተት በግልጽ ምርጫ መፍጠር ይችላሉ።', changedConflict: 'ክስተቱ ከPlanora ውጭ ተቀይሯል። ለመተካት ከመምረጥዎ በፊት ይገምግሙት።', createAgain: 'አዲስ ክስተት ፍጠር', replaceExternal: 'በPlanora ዝርዝሮች ተካ',
  },
  sync: {
    eyebrow: 'ግላዊነት እና ውሂብ', title: 'ግላዊነት እና ውሂብ', description: 'ውሂብዎን ይላኩ ወይም ያስወግዱ፤ ከግልጽ ምርጫ በኋላም ዕቅድን በፈቃድ ያመሳስሉ።', settingsTitle: 'ግላዊነት እና ውሂብ', settingsDescription: 'የአካባቢ ውሂብ፣ ተንቀሳቃሽ ወጪ፣ አማራጭ ማመሳሰል እና የመለያ ስረዛን ያስተዳድሩ።', manage: 'ግላዊነትን እና ውሂብን ያስተዳድሩ', localOnly: 'በመሣሪያው ብቻ', enabled: 'ማመሳሰል ነቅቷል', localFirst: 'SQLite ፈጣን የመረጃ ምንጭ ሆኖ ይቆያል። መደበኛ ዕቅድ አውታረ መረብን አይጠብቅም።', status: 'የማመሳሰል ሁኔታ', stateLocal: 'በመሣሪያው ብቻ። ምንም አይላክም።', stateIdle: 'ከመጨረሻው የተጠናቀቀ ማረጋገጫ በኋላ ዘምኗል።', stateSyncing: 'የተገደበ ስብስብ እየተመሳሰለ ነው።', stateOffline: 'ከመስመር ውጭ። የሚጠባበቁ ለውጦች በደህና ተሰልፈዋል።', stateError: 'ማመሳሰሉ ሌላ ሙከራ ይፈልጋል። የአካባቢ ዕቅድ አሁንም ይገኛል።', stateConflict: 'አንድ ወይም ከዚያ በላይ ለውጦች ምርጫዎን ይፈልጋሉ።', stateRestoring: 'የተገደበ ስብስብ ወደ አካባቢ ማከማቻ እየተመለሰ ነው።', stateAccountMismatch: 'ሌላ መለያ ስለገባ ማመሳሰል ቆሟል።', pendingCount: '{{count}} የአካባቢ ለውጦች ተሰልፈዋል', lastSuccess: 'የመጨረሻ የተጠናቀቀ ማረጋገጫ፦ {{value}}', recoverableError: 'የርቀት ጥያቄው አልተጠናቀቀም። የአካባቢ ውሂብ አልተወገደም።', syncNow: 'አሁን ያመሳስሉ', disable: 'ማመሳሰልን ያጥፉ', upload: 'ይህን መሣሪያ ይላኩ', merge: 'ከደመና ቦታ ጋር ያዋህዱ', restore: 'የደመና ቦታን ይመልሱ', activationNote: 'መግባት ይህን በራስ-ሰር አያነቃም። መላክ ይህን መሣሪያ መነሻ ያደርጋል፤ ማዋሃድ የአካባቢ መዝገቦችን ይጠብቃል፤ መመለስ የባለቤትነት መዝገቦችን ያወርዳል።', signInRequired: 'መጀመሪያ ይግቡ፣ ከዚያ ግልጽ የማመሳሰል ምርጫ ለማድረግ ወደዚህ ይመለሱ።', unavailable: 'የርቀት መለያ አገልግሎቶች አልተዋቀሩም። የአካባቢ ዕቅድ ሙሉ በሙሉ ይገኛል።', reviewConflicts: 'ግጭቶችን ይመልከቱ ({{count}})', conflictEyebrow: 'የእርስዎ ምርጫ', conflictTitle: 'የተመሳሰሉ ለውጦችን ይፍቱ', conflictDescription: 'ምን እንደሚቆይ እስኪመርጡ ድረስ ሁለቱም ስሪቶች ይጠበቃሉ።', conflictItem: 'የ{{type}} ለውጥ', conflictBasis: 'የአካባቢ ክለሳ {{local}} እና የደመና ክለሳ {{remote}} በተናጠል ተለውጠዋል።', keepLocal: 'የአካባቢ ስሪትን ያቆዩ', keepCloud: 'የደመና ስሪትን ያቆዩ', combineText: 'የሚደገፍ ጽሑፍ ያዋህዱ', noConflicts: 'አሁን መፍትሔ የሚፈልግ ለውጥ የለም።', exportTitle: 'ተንቀሳቃሽ ወጪ', exportDescription: 'የመግቢያ መረጃ ወይም የመሣሪያ ማሳወቂያና ቀን መቁጠሪያ መለያዎች የሌሉበት የዕቅድ ውሂብ JSON ቅጂ ይፍጠሩ።', exportAction: 'የዕቅድ ውሂብን ይላኩ', exportDialog: 'የPlanora ዕቅድ ውሂብን ይላኩ', deletionTitle: 'የማስወገድ መቆጣጠሪያዎች', deletionDescription: 'እነዚህ ድርጊቶች የተለያዩ ናቸው። ያልተሳካ የርቀት ድርጊት ተጠናቋል ተብሎ አይታወቅም።', clearDevice: 'የዕቅድ ውሂብን ከዚህ መሣሪያ ያጽዱ', deleteCloud: 'የተመሳሰለ የደመና ውሂብን ይሰርዙ', deleteAccount: 'የPlanora መለያን ይሰርዙ', confirmTitle: 'የማረጋገጫ ሐረጉን ይጻፉ', confirmClear: 'CLEAR ይጻፉ። ይህ የዕቅድ መዝገቦችን ከመሣሪያው ያስወግዳል፤ የደመና ውሂብን ወይም መለያን አይሰርዝም።', confirmCloud: 'DELETE CLOUD ይጻፉ። ይህ የተመሳሰሉ መዝገቦችን ከመለያው ያስወግዳል፣ መለያውንና የመሣሪያውን ውሂብ ግን ይጠብቃል።', confirmAccount: 'DELETE ACCOUNT ይጻፉ። አገልጋዩ የገባውን መለያ መሰረዝ አለበት። የመሣሪያ ውሂብ በተለየ እስኪጸዳ ድረስ ይቆያል።', confirmation: 'የማረጋገጫ ሐረግ', completedTitle: 'ድርጊቱ ተጠናቋል', deviceCleared: 'የዕቅድ ውሂብ ከዚህ መሣሪያ ተጽድቷል።', cloudDeleted: 'የተመሳሰለ የደመና ውሂብ ተሰርዟል።', accountDeleted: 'የመለያ ስረዛ ጥያቄው ተጠናቋል። የመሣሪያ ውሂብ በራስ-ሰር አልተወገደም።',
    statePending: 'ለማመሳሰል በመጠባበቅ ላይ። የአካባቢ ለውጦች በደህና ተሰልፈዋል።',
    statePendingOffline: 'ግንኙነትን በመጠባበቅ ላይ። የአካባቢ ለውጦች በደህና ተሰልፈዋል።',
  },
  entityTypes: {
    workspace: 'የሥራ ቦታ', task: 'ተግባር', planBlockSeries: 'ተደጋጋሚ ዕቅድ', planBlock: 'የዕቅድ ክፍል', routine: 'ልማድ', routineCheckIn: 'የልማድ ምዝገባ', goal: 'ግብ', milestone: 'ደረጃ', goalRoutineLink: 'የግብና ልማድ አገናኝ', area: 'አካባቢ', tag: 'መለያ', reflection: 'ነጸብራቅ', appSettings: 'የዕቅድ ምርጫዎች', reminderIntent: 'የማስታወሻ ምርጫ',
  },
  recoveryBoundary: {
    title: 'ይህ ክፍል ሌላ ሙከራ ይፈልጋል', description: 'የተቀመጠው የአካባቢ ውሂብዎ አልተቀየረም። ክፍሉን እንደገና ይክፈቱ ወይም ወደ ዛሬ ይመለሱ።', retry: 'ይህን ክፍል እንደገና ሞክር', retryHint: 'የአካባቢ ውሂብን ሳያጠፋ ይህን ክፍል ብቻ እንደገና ይጀምራል።', today: 'ወደ ዛሬ ተመለስ', todayHint: 'ይህን ክፍል ትቶ ዛሬን ይከፍታል።',
  },
  notFound: {
    eyebrow: 'ደህንነቱ የተጠበቀ መመለሻ', title: 'ያ መድረሻ አይገኝም', description: 'አገናኙ ያልተሟላ ሊሆን ወይም ከሚገኝ መዝገብ ጋር ላይገናኝ ይችላል። የተቀመጠው ውሂብዎ አልተቀየረም።', today: 'ዛሬን ክፈት',
  },
  destructive: {
    clearDevice: 'የመሣሪያ ውሂብ አጥፋ', deleteCloud: 'የደመና ውሂብ አጥፋ', deleteAccount: 'መለያ አጥፋ', calendarStateHint: 'የተገናኙ የመሣሪያ ቀን መቁጠሪያ ክስተቶችም ይወገዱ እንደሆነ ይምረጡ።',
  },
  nativePermissions: {
    reminderChannel: 'የPlanora ማስታወሻዎች', reminderChannelDescription: 'በPlanora ውስጥ በግልጽ የመረጧቸው ማስታወሻዎች',
  },
  settings: {
    eyebrow: 'የእርስዎ ቦታ', title: 'ቅንብሮች', description: 'Planora እንዴት እንደሚታይና እንደሚሠራ ከመጀመሪያው በተደራሽ ምርጫዎች ያስተካክሉ።', language: 'ቋንቋ', languageDescription: 'ለዚህ የአካባቢ መገለጫ የመተግበሪያ ቋንቋ ይምረጡ።', systemLanguage: 'የመሣሪያውን ቋንቋ ተጠቀም', directionRestart: 'የቀኝ ወደ ግራ አቀማመጥን በመተግበሪያው ሁሉ ለመተግበር Planoraን እንደገና ያስጀምሩ። Expo Go ይህን ምርጫ ሊመልስ ይችላል፤ የRTL ማረጋገጫ ለማድረግ የልማት ስሪት ይጠቀሙ።', planning: 'የእቅድ ምርጫዎች', planningDescription: 'የሥራ ጫናን ለማነጻጸር የተረጋጋ ዕለታዊ አቅም ይወስኑ።', capacity: 'ዕለታዊ አቅም በደቂቃ', capacityHint: 'ከ30 እስከ 1,440 ደቂቃ ይምረጡ።', saveCapacity: 'አቅም አስቀምጥ', saved: 'ምርጫው ተቀምጧል።',
  },
  storage: {
    title: 'ውሂብ እና ማከማቻ', description: 'የእቅድ መሠረትዎ በዚህ መሣሪያ ላይ ይኖራል።', localData: 'የአካባቢ ውሂብ', localReady: 'በዚህ መሣሪያ ላይ ይገኛል', localPreparing: 'ተደራሽነት እየተዘጋጀ ነው', offline: 'ከመስመር ውጭ ዝግጁነት', offlineReady: 'ከመስመር ውጭ ለመጠቀም ዝግጁ', offlinePreparing: 'ዝግጅት እየተጠናቀቀ ነው', state: 'የማከማቻ ሁኔታ', ready: 'ዝግጁ', preparing: 'በመዘጋጀት ላይ', errorTitle: 'የአካባቢ ማከማቻ ሌላ ሙከራ ይፈልጋል', retryLabel: 'የአካባቢ ማከማቻን እንደገና ለማዘጋጀት ሞክር',
  },
  validation: {
    reflectionBody: 'ከማስቀመጥዎ በፊት ነጸብራቅ ይጻፉ።', reflectionLength: '8,000 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', reflectionDate: 'ትክክለኛ የነጸብራቅ ቀን ይምረጡ።', reflectionScope: 'ይህ የነጸብራቅ አይነት መለያ አይጠቀምም።', reflectionMood: 'የሚገኝ የስሜት መለያ ይምረጡ።', reflectionDuplicate: 'ለዚህ ጊዜ ነጸብራቅ አስቀድሞ አለ።',
    goalTitle: 'የግብ ርዕስ ያስገቡ።', milestoneTitle: 'የደረጃ ርዕስ ያስገቡ።', percentage: 'ከ0 እስከ 100 ያለ ሙሉ መቶኛ ያስገቡ።', activeArea: 'ከዚህ የሥራ ቦታ ንቁ አካባቢ ይምረጡ።', availableGoal: 'ከዚህ የሥራ ቦታ የሚገኝ ግብ ይምረጡ።',
    taskTitle: 'የተግባር ርዕስ ያስገቡ።', blockTitle: 'የጊዜ ክፍል ርዕስ ያስገቡ።', routineTitle: 'የልማድ ርዕስ ያስገቡ።', titleLength: '200 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', notesLength: '4,000 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።', date: 'በYYYY-MM-DD ቅርጸት ትክክለኛ ቀን ይጠቀሙ።', startDate: 'ትክክለኛ የመጀመሪያ ቀን ይጠቀሙ።', endDate: 'ትክክለኛ የመጨረሻ ቀን ይጠቀሙ።', time: 'በHH:MM ቅርጸት ትክክለኛ ጊዜ ይጠቀሙ።', startTime: 'በHH:MM ቅርጸት ትክክለኛ የመጀመሪያ ጊዜ ይጠቀሙ።', endTime: 'በHH:MM ቅርጸት ትክክለኛ የመጨረሻ ጊዜ ይጠቀሙ።', endAfterStart: 'የመጨረሻ ጊዜ ከመጀመሪያ ጊዜ በኋላ መሆን አለበት።', nonexistentTime: 'በዚህ ቀን የሚኖር የአካባቢ ጊዜ ይምረጡ።', scheduledNeedsDate: 'ለታቀደ ጊዜ የመድረሻ ቀን ይምረጡ።', weekdays: 'ቢያንስ አንድ የሳምንት ቀን ይምረጡ።', interval: 'የድግግሞሽ ርቀት ከ1 እስከ 365 መሆን አለበት።', capacity: 'ከ30 እስከ 1,440 ሙሉ ቁጥር ይምረጡ።', emailRequired: 'ኢሜይልዎን ያስገቡ።', emailComplete: 'ሙሉ የኢሜይል አድራሻ ያስገቡ።', passwordRequired: 'የይለፍ ቃልዎን ያስገቡ።', passwordLength: 'ቢያንስ ስምንት ቁምፊዎች ይጠቀሙ።', displayNameRequired: 'የሚታይ ስም ያስገቡ።', displayNameLength: '60 ወይም ከዚያ ያነሱ ቁምፊዎችን ይጠቀሙ።',
    passwordsMatch: 'የይለፍ ቃሎቹ አይመሳሰሉም።',
  },
  errors: {
    insightsRefresh: 'Planora ግንዛቤዎችን ማደስ አልቻለም። የተቀመጠው የአካባቢ ውሂብ አልተቀየረም።', reflectionRevision: 'ይህ ነጸብራቅ ዝማኔዎ ከመቀመጡ በፊት ተቀይሯል። ያድሱና እንደገና ይሞክሩ።', reflectionSave: 'የነጸብራቅ ለውጡን ማስቀመጥ አልተቻለም። ያድሱና ይሞክሩ።', reflectionUnavailable: 'ነጸብራቁ ከእንግዲህ አይገኝም።',
    goalsRefresh: 'Planora ግቦችን ማደስ አልቻለም። የተቀመጠው ውሂብ አልተቀየረም።', goalRevision: 'ይህ ግብ ከመቀመጡ በፊት ተቀይሯል። ያድሱና እንደገና ይሞክሩ።', goalSave: 'የግቡን ለውጥ ማስቀመጥ አልተቻለም። ያድሱና ይሞክሩ።', goalUnavailable: 'ግቡ ከእንግዲህ አይገኝም።', goalTaskActionable: 'ተፈጻሚ ተግባራት ብቻ ሊገናኙ ይችላሉ።', goalTaskOwned: 'ይህ ተግባር ሌላ ግብ ይደግፋል።', goalTaskMissing: 'ይህ ተግባር ከግቡ ጋር አልተገናኘም።', goalNextAction: 'ከዚህ ግብ ጋር የተገናኘ ተፈጻሚ ተግባር ይምረጡ።', goalRoutineActive: 'ከዚህ የሥራ ቦታ ንቁ ልማድ ይምረጡ።',
    refreshDay: 'Planora ይህን ቀን ማደስ አልቻለም። የተቀመጠው የአካባቢ ውሂብዎ አልተቀየረም።', revision: 'ዝማኔዎ ከመቀመጡ በፊት ይህ ንጥል ተቀይሯል። ያድሱና እንደገና ይሞክሩ።', save: 'ያ ለውጥ ሊቀመጥ አልቻለም። ቀኑን ያድሱና እንደገና ይሞክሩ።', onboardingRead: 'Planora የመግቢያ ምርጫዎችን ማንበብ አልቻለም። የአካባቢ ውሂብዎ አሁንም ይገኛል።', onboardingSave: 'Planora ይህን ምርጫ ማስቀመጥ አልቻለም። እንደገና ይሞክሩ።', workspace: 'Planora የአካባቢ የእቅድ ቦታዎን ማዘጋጀት አልቻለም። ውሂብዎ አልተቀየረም።', generic: 'ትንሽ ይጠብቁና እንደገና ይሞክሩ።',
    invalidCredentials: 'ኢሜይሉ ወይም የይለፍ ቃሉ አልተቀበለም። ሁለቱንም ይፈትሹና ደግመው ይሞክሩ።', emailUnverified: 'ከመግባትዎ በፊት ኢሜይልዎን ያረጋግጡና ደግመው ይሞክሩ።', emailInUse: 'ይህ ኢሜይል ለአዲስ መለያ መጠቀም አይቻልም። ለመግባት ይሞክሩ።', weakPassword: 'ቢያንስ ስምንት ቁምፊ ያለው ጠንካራ የይለፍ ቃል ይምረጡ።', networkUnavailable: 'Planora የመለያ አገልግሎቱን ማግኘት አልቻለም። ግንኙነትዎን ይፈትሹና ደግመው ይሞክሩ።', rateLimited: 'ብዙ ሙከራዎች ተደርገዋል። ትንሽ ይጠብቁና ደግመው ይሞክሩ።', expiredLink: 'ይህ የመልሶ ማግኛ አገናኝ ከእንግዲህ ትክክለኛ አይደለም። አዲስ አገናኝ ይጠይቁ።', serviceUnavailable: 'የመለያ አገልግሎቶች ለጊዜው አይገኙም። የአካባቢ ውሂብዎ አልተነካም።', accountUnknown: 'በመለያ ጥያቄው ላይ ችግር ተፈጥሯል። የአካባቢ ውሂብዎ አልተነካም።', linkTask: 'ከዚህ የሥራ ቦታ የሚገኝ ተግባር ይምረጡ።', linkRoutine: 'ከዚህ የሥራ ቦታ የሚገኝ ልማድ ይምረጡ።', linkEither: 'ተግባር ወይም ልማድ ያገናኙ፣ ሁለቱንም አይደለም።', endBeforeStart: 'የመጨረሻ ቀን ከመጀመሪያ ቀን በፊት መሆን አይችልም።', recurrenceConflict: 'ይህ ድግግሞሽ ተቀይሯል። ያድሱና ደግመው ይሞክሩ።', recurrenceWindow: 'የድግግሞሽ መስኮቶች በ56 ቀናት የተገደቡ ናቸው።',
    scheduleRefresh: 'የጊዜ ሰሌዳዎን ማደስ አልተቻለም። የተቀመጠው የአካባቢ ውሂብ አልተቀየረም።', scheduleRevision: 'ማሻሻያዎ ከመቀመጡ በፊት ይህ የጊዜ ሰሌዳ ተቀይሯል። ያድሱና ደግመው ይሞክሩ።', scheduleSave: 'የጊዜ ሰሌዳውን ለውጥ ማስቀመጥ አልተቻለም። ያድሱና ደግመው ይሞክሩ።',
  },
  placeholders: {
    goalsDescription: 'የረጅም ጊዜ ፍላጎቶችን ወደሚታዩ ምዕራፎችና ተግባራዊ ቀጣይ እርምጃዎች ይቀይሩ።', goalsEmpty: 'ትርጉም ያለው እድገት እዚህ ይጀምራል', goalsEmptyDescription: 'የግብ መንገዶች፣ ምዕራፎችና የእድገት ምዝገባዎች ለተለየ የባህሪ ደረጃ ታቅደዋል።', insightsDescription: 'የግል ውሂብዎን ግልጽና የግል አድርገው ጠቃሚ ቅጦችን ይመልከቱ።', insightsEmpty: 'ቅጦችዎ ታሪክ ይናገራሉ', insightsEmptyDescription: 'ለማጠቃለል በቂ እንቅስቃሴ ሲኖር አዝማሚያዎችና ማሰላሰሎች ይታያሉ።',
  },
} satisfies TranslationCatalog;
