export const en = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    continue: 'Continue',
    create: 'Create',
    delete: 'Delete',
    done: 'Done',
    edit: 'Edit',
    goBack: 'Go back',
    keep: 'Keep',
    loading: 'Loading',
    noNotes: 'No notes',
    none: 'None',
    refresh: 'Refresh',
    retry: 'Try again',
    save: 'Save',
    skip: 'Skip',
    today: 'Today',
    tomorrow: 'Tomorrow',
    yesterday: 'Yesterday',
    active: 'Active',
    paused: 'Paused',
    archived: 'Archived',
    planned: 'Planned',
    completed: 'Completed',
    cancelled: 'Cancelled',
    pending: 'Pending',
    inProgress: 'In progress',
    skipped: 'Skipped',
    anyTime: 'Any time today',
    minuteOne: '{{count}} minute',
    minuteOther: '{{count}} minutes',
    hourOne: '{{count}} hour',
    hourOther: '{{count}} hours',
  },
  launch: {
    starting: 'Planora is starting',
    tagline: 'Make space for what matters.',
    storage: 'Preparing local storage.',
    account: 'Restoring your account.',
    preferences: 'Loading your preferences.',
    workspace: 'Preparing your planning space.',
  },
  tabs: {
    today: 'Today',
    planner: 'Planner',
    goals: 'Goals',
    insights: 'Insights',
    settings: 'Settings',
  },
  auth: {
    chooseTitle: 'Choose what fits today',
    chooseDescription: 'Keep using Planora locally, or add an account for a small profile and account recovery. Planning content stays on this device.',
    localTitle: 'Continue locally',
    localDescription: 'No account is required. Your existing local planning data remains ready offline.',
    accountTitle: 'Optional account',
    accountDescription: 'Create a profile or sign in. This does not upload, merge, or replace local planning records.',
    accountUnavailable: 'Account services are not configured in this build. Local-only use remains available.',
    createAccount: 'Create account',
    signIn: 'Sign in',
    signInTitle: 'Welcome back',
    signInDescription: 'Sign in to your optional Planora account. Your local planning space remains separate and available.',
    createTitle: 'Create your account',
    createDescription: 'Create a minimal account profile for sign-in and recovery. Planning content is not sent to the account service.',
    displayName: 'Display name',
    displayNamePlaceholder: 'How you want to be addressed',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    confirmPassword: 'Confirm password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    alreadyAccount: 'Already have an account? Sign in',
    createInstead: 'Create an account',
    forgotPassword: 'Forgot password?',
    recoveryEyebrow: 'ACCOUNT RECOVERY',
    recoveryTitle: 'Reset your password',
    recoveryDescription: 'Enter your email and we will request a recovery message without revealing whether an account exists.',
    sendRecovery: 'Send recovery instructions',
    secureRecovery: 'SECURE RECOVERY',
    choosePassword: 'Choose a new password',
    choosePasswordDescription: 'Choose a new password for your account. This does not change or remove local planning data.',
    savePassword: 'Save new password',
    checkEmailEyebrow: 'CHECK YOUR EMAIL',
    checkEmailTitle: 'One more step',
    checkEmailDescription: 'If the address can receive the requested message, follow the link in that message to continue.',
    inboxTitle: 'The next step happens in your inbox',
    returnSignIn: 'Return to sign in',
    recoveryValidating: 'Planora is validating the recovery link without showing its private session details.',
    requestNewLink: 'Request a new link',
    issueEyebrow: 'RECOVERABLE ISSUE',
    issueTitle: "Let's try another path",
    issueDescription: 'The account request did not complete, but your local Planora data is safe and remains available.',
    accountOptions: 'Back to account options',
    profileEyebrow: 'ACCOUNT PROFILE',
    editProfile: 'Edit profile',
    profileDescription: 'This small account profile is separate from your local planning records.',
    profileScope: 'Profile scope',
    saveProfile: 'Save profile',
    signOut: 'Sign out',
    signOutTitle: 'Sign out of your account?',
    signOutDescription: 'Your planning data stays on this device and remains available after sign-out.',
    accountLabel: 'Account',
    accountSettingsDescription: 'Account features are optional and stay separate from local planning data.',
    planoraAccount: 'Planora account',
    localOnly: 'Local-only',
    localOnlyDescription: 'No account is required to use the main planning tabs.',
    emailVerified: 'Email verified',
    emailPending: 'Email verification pending',
    viewOnboarding: 'View onboarding again',
    newToAccount: 'New to account features?',
    passwordPrivacy: 'Your password is sent securely to the account provider and is never stored in Planora\'s local planning database.',
    recoveryPrivacy: 'For privacy, the confirmation screen is the same for every valid email format.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
  onboarding: {
    pageOneEyebrow: 'A CALMER START',
    pageOneTitle: 'Your day, with room to breathe',
    pageOneDescription: 'Planora brings tasks and routines into a quiet daily view while keeping the rest of your planning spaces close.',
    pageOneDetail: 'Capture tasks and check in with routines without creating an account.',
    pageTwoEyebrow: 'LOCAL BY DEFAULT',
    pageTwoTitle: 'Ready when the network is not',
    pageTwoDescription: 'Your planning foundation is stored on this device and remains available offline. Local actions never wait for an account service.',
    pageTwoDetail: 'Local data survives app restarts and stays separate from account sessions.',
    pageThreeEyebrow: 'YOUR CHOICE',
    pageThreeTitle: 'An account is optional',
    pageThreeDescription: 'Create an account for profile and recovery access, or continue locally. Planning content is not uploaded or synchronized.',
    pageThreeDetail: 'You can sign in later from Settings without changing local identifiers.',
    close: 'Close onboarding',
    skip: 'Skip onboarding',
    step: 'Step {{current}} of {{total}}',
    stepAnnouncement: 'Step {{current}} of {{total}}. {{title}}',
    startLocally: 'Start locally',
  },
  today: {
    greeting: 'A clear view of today',
    subtitle: 'Choose what matters, then leave room for the day to move.',
    quickPlaceholder: 'Add a task for today',
    quickLabel: 'Quick add task',
    quickHint: 'Creates a task due today',
    add: 'Add',
    progress: '{{completed}} of {{total}} complete',
    workload: '{{planned}} planned · {{remaining}} remaining',
    nextUp: 'Next up',
    priority: 'Priority and overdue',
    remaining: "Today's tasks",
    routines: 'Scheduled routines',
    agenda: 'Agenda preview',
    completed: 'Completed',
    showCompleted: 'Show completed items',
    hideCompleted: 'Hide completed items',
    quietEmpty: 'Nothing needs your attention yet.',
    noPriority: 'No priority or overdue tasks.',
    noRemaining: 'No remaining tasks for today.',
    noRoutines: 'No routines are scheduled today.',
    noAgenda: 'No time blocks are planned yet.',
    allTasks: 'All tasks',
    allRoutines: 'Routines',
    openPlanner: 'Open Planner',
    moreActions: 'More actions',
    loading: 'Loading your day.',
    refreshTitle: 'Your day needs a refresh',
    failed: 'Your day could not be loaded.',
    completedToday: 'Completed today',
    skippedToday: 'Skipped today',
    markComplete: 'Mark complete',
    markSkipped: 'Mark skipped',
    undo: 'Undo check-in',
    overdue: 'Overdue',
    dueToday: 'Due today',
    unscheduled: 'Inbox',
  },
  tasks: {
    title: 'All tasks',
    new: 'New task',
    details: 'Task details',
    createDescription: 'Add what matters, then shape its timing only if helpful.',
    editDescription: 'Update the task without changing its stable local identity.',
    loading: 'Loading task details.',
    refreshTitle: 'Task details need a refresh',
    listRefresh: 'Your task list needs a refresh',
    notLoaded: 'The task could not be loaded.',
    unavailable: 'Task not available',
    unavailableDescription: 'It may have been removed or changed. Return to Today and refresh.',
    emptyTitle: 'No tasks yet',
    emptyDescription: 'Quick captures and full tasks will stay available here.',
    createAction: 'Create a task',
    actions: 'Task actions',
    complete: 'Complete task',
    reopen: 'Reopen task',
    cancel: 'Cancel task',
    delete: 'Delete task',
    cancelTitle: 'Cancel task?',
    cancelDescription: 'The task will move out of active daily sections and can be reopened later.',
    keep: 'Keep task',
    deleteTitle: 'Delete task?',
    deleteDescription: 'This removes the task from your daily views. This action cannot be undone here.',
    overdue: 'Overdue',
    upcoming: 'Upcoming',
    unscheduled: 'Unscheduled',
    opensDetails: 'Opens task details',
    titleField: 'Title',
    notesField: 'Notes',
    priorityField: 'Priority',
    statusField: 'Status',
    dueDate: 'Due date',
    dueDateHint: 'Use YYYY-MM-DD, or leave blank.',
    scheduledTime: 'Scheduled time',
    timeHint: 'Use 24-hour HH:MM, or leave blank.',
    priorityNone: 'No priority',
    priorityLow: 'Low priority',
    priorityMedium: 'Medium priority',
    priorityHigh: 'High priority',
  },
  routines: {
    title: 'Routines',
    new: 'New routine',
    details: 'Routine details',
    description: 'Build a light daily or weekly rhythm without reminders or scoring.',
    loading: 'Loading routine details.',
    refreshTitle: 'Routine details need a refresh',
    listRefresh: 'Your routine list needs a refresh',
    notLoaded: 'The routine could not be loaded.',
    unavailable: 'Routine not available',
    unavailableDescription: 'Return to Today and refresh your local planning data.',
    emptyTitle: 'No routines yet',
    emptyDescription: 'Create a daily rhythm or choose the weekdays that fit.',
    createAction: 'Create a routine',
    opensDetails: 'Opens routine details',
    schedule: 'Schedule',
    everyDay: 'Every day',
    selectedDays: 'Selected days',
    weekdays: 'Weekdays',
    preferredTime: 'Preferred time',
    state: 'Routine state',
  },
  planner: {
    title: 'Planner',
    day: 'Day',
    week: 'Week',
    previousDay: 'Previous day',
    nextDay: 'Next day',
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    currentWeek: 'Current week',
    date: 'Date',
    timeline: 'Daily timeline',
    newBlock: 'New time block',
    editBlock: 'Edit time block',
    blockDetails: 'Time block details',
    unscheduledTasks: 'Unscheduled tasks',
    scheduleTask: 'Schedule task',
    noBlocks: 'No time blocks are planned for this day.',
    noTasks: 'All actionable tasks have a time block.',
    workload: 'Workload',
    plannedMinutes: '{{duration}} planned',
    remainingCapacity: '{{duration}} remaining',
    overCapacity: '{{duration}} beyond your daily capacity',
    withinCapacity: 'Within your daily capacity',
    overlapOne: '{{count}} overlap',
    overlapOther: '{{count}} overlaps',
    unscheduledOne: '{{count}} unscheduled task',
    unscheduledOther: '{{count}} unscheduled tasks',
    blockOne: '{{count}} block',
    blockOther: '{{count}} blocks',
    taskOne: '{{count}} task',
    taskOther: '{{count}} tasks',
    overlapWarning: 'This block overlaps another block. You can keep it or change the time.',
    overlapCounted: 'Overlapping blocks are counted separately in planned time.',
    overloaded: 'Over capacity',
    linkedTask: 'Linked task',
    linkedRoutine: 'Linked routine',
    removeLink: 'Remove link',
    completeBlock: 'Complete block',
    reopenBlock: 'Reopen block',
    cancelBlock: 'Cancel block',
    deleteBlock: 'Delete block',
    deleteTitle: 'Delete time block?',
    deleteDescription: 'This removes only this scheduled block. Linked tasks and routines remain available.',
    cancelTitle: 'Cancel time block?',
    cancelDescription: 'Cancelled blocks stay in history and stop counting toward capacity.',
    keepBlock: 'Keep block',
    startTime: 'Start time',
    endTime: 'End time',
    titleField: 'Title',
    notesField: 'Notes',
    statusField: 'Status',
    repeat: 'Repeat',
    repeatNone: 'Does not repeat',
    repeatDaily: 'Daily',
    repeatWeekly: 'Weekly',
    repeatInterval: 'Repeat interval',
    repeatEnd: 'Repeat end date',
    editOccurrence: 'Edit this occurrence',
    editFuture: 'Edit this and future occurrences',
    recurrenceBounded: 'Occurrences are prepared in a rolling eight-week window.',
    move: 'Move or reschedule',
    selectedDay: 'Selected day',
    currentTime: 'Current time',
    capacitySummary: '{{planned}} planned out of {{capacity}} capacity',
    loading: 'Loading your schedule.',
    refreshTitle: 'Your schedule needs a refresh',
  },
  goals: {
    heading: 'Goals',
    summaryActive: '{{count}} active',
    create: 'Create goal',
    edit: 'Edit goal',
    details: 'Goal details',
    formDescription: 'Shape a clear direction without turning it into a scorecard.',
    titleField: 'Title',
    descriptionField: 'Description',
    motivationField: 'Why this matters',
    area: 'Area',
    horizon: 'Horizon',
    horizonMonth: 'Month',
    horizonQuarter: 'Quarter',
    horizonYear: 'Year',
    horizonSomeday: 'Someday',
    targetDate: 'Target date',
    targetDateHint: 'Use YYYY-MM-DD, or leave blank.',
    status: 'Status',
    statusActive: 'Active',
    statusPaused: 'Paused',
    statusCompleted: 'Completed',
    statusAbandoned: 'Abandoned',
    progressMethod: 'Progress method',
    progressMilestones: 'Milestones',
    progressTasks: 'Linked tasks',
    progressManual: 'Manual percentage',
    progressNone: 'No numeric progress',
    manualProgress: 'Manual progress',
    manualHint: 'Enter a whole percentage from 0 through 100.',
    loading: 'Loading goals.',
    refreshTitle: 'Goals need a refresh',
    notLoaded: 'Goals could not be loaded. Your saved data is unchanged.',
    unavailable: 'Goal not available',
    unavailableDescription: 'It may have been removed or changed. Return to Goals and refresh.',
    emptyTitle: 'Make room for one meaningful direction',
    emptyDescription: 'Create a goal when a longer path would benefit from a calm next step.',
    search: 'Search goals',
    noMatches: 'No goals match this search or filter.',
    filterCurrent: 'Current',
    filterCompleted: 'Completed',
    filterAll: 'All',
    activeGoals: 'Active goals',
    pausedGoals: 'Paused goals',
    completedGoals: 'Completed goals',
    somedayGoals: 'Someday goals',
    abandonedGoals: 'Abandoned goals',
    noTargetDate: 'No target date',
    targetContext: 'Target {{date}}',
    nextMilestone: 'Next milestone',
    nextAction: 'Next action',
    notStarted: 'Not started',
    progressCount: '{{completed}} of {{total}} complete',
    percentComplete: '{{percent}} complete',
    noNumericProgress: 'Progress follows the next useful step.',
    opensDetails: 'Opens goal details',
    motivation: 'Why it matters',
    milestones: 'Milestones',
    linkedTasks: 'Linked next actions',
    supportingRoutines: 'Supporting routines',
    addMilestone: 'Add milestone',
    linkTask: 'Link task',
    linkRoutine: 'Link routine',
    createTask: 'Create task for goal',
    noMilestones: 'No milestones yet.',
    noTasks: 'No tasks are linked.',
    noRoutines: 'No routines support this goal yet.',
    milestoneTitle: 'Milestone title',
    milestoneNotes: 'Notes',
    milestoneDate: 'Target date',
    milestonePending: 'Pending',
    milestoneCompleted: 'Completed',
    milestoneCancelled: 'Cancelled',
    newMilestone: 'New milestone',
    editMilestone: 'Edit milestone',
    completeMilestone: 'Complete milestone',
    reopenMilestone: 'Reopen milestone',
    cancelMilestone: 'Cancel milestone',
    deleteMilestone: 'Delete milestone',
    moveUp: 'Move up',
    moveDown: 'Move down',
    moveUpHint: 'Moves this milestone earlier in the goal.',
    moveDownHint: 'Moves this milestone later in the goal.',
    setNextAction: 'Set as next action',
    clearNextAction: 'Clear next action',
    unlinkTask: 'Unlink task',
    unlinkRoutine: 'Unlink routine',
    routineCompletedToday: 'Completed today',
    routineSkippedToday: 'Skipped today',
    routinePendingToday: 'Pending today',
    actions: 'Goal actions',
    pause: 'Pause goal',
    resume: 'Resume goal',
    complete: 'Complete goal',
    reopen: 'Reopen goal',
    abandon: 'Abandon goal',
    delete: 'Delete goal',
    pauseTitle: 'Pause this goal?',
    pauseDescription: 'The goal will stay available without appearing as active.',
    completeTitle: 'Complete this goal?',
    completeDescription: 'This records completion without changing linked tasks or routines.',
    abandonTitle: 'Abandon this goal?',
    abandonDescription: 'The goal will leave current sections while its related records remain intact.',
    deleteTitle: 'Delete this goal?',
    deleteDescription: 'The goal leaves your views. Linked tasks and routines remain available.',
    deleteMilestoneTitle: 'Delete this milestone?',
    deleteMilestoneDescription: 'This removes the milestone from the goal. Other goal records remain intact.',
    keepGoal: 'Keep goal',
    keepMilestone: 'Keep milestone',
    chooseTask: 'Choose a task',
    chooseRoutine: 'Choose a routine',
    availableTasks: 'Available actionable tasks',
    availableRoutines: 'Available active routines',
    noAvailableTasks: 'No unlinked actionable tasks are available.',
    noAvailableRoutines: 'No unlinked active routines are available.',
    completionSuggestion: 'All milestones are complete. Complete the goal when it feels finished.',
    needsAttention: 'Needs attention',
    linkedGoal: 'Goal: {{title}}',
    openGoal: 'Open goal {{title}}',
  },
  insights: {
    heading: 'Insights',
    description: 'Understand your local planning activity with calm, factual summaries.',
    destination: 'Insight section',
    summary: 'Summary',
    trends: 'Trends',
    reflections: 'Reflections',
    range: 'Time range',
    last7Days: 'Last 7 days',
    last4Weeks: 'Last 4 weeks',
    last12Weeks: 'Last 12 weeks',
    periodDates: '{{start}} to {{end}}',
    partialPeriod: 'The current period includes today and may still change. The comparison period has the same number of calendar days.',
    loading: 'Loading local insights.',
    refreshTitle: 'Insights need a refresh',
    partialData: 'The latest refresh did not finish. These are the last locally loaded results.',
    localPrivacy: 'Calculated on this device from the active workspace. No planning or reflection data is sent for analytics.',
    noActivityTitle: 'Not enough activity yet',
    noActivity: 'There is no recorded activity in this period. Current task and goal context remains available.',
    tasksCompleted: 'Tasks completed',
    tasksCompletedBasis: 'Tasks with a completion timestamp inside the selected period.',
    actionableRemaining: 'Actionable tasks remaining',
    actionableRemainingBasis: 'Current pending and in-progress tasks in this workspace.',
    completionRatio: 'Task completion ratio',
    completionRatioBasis: 'Completed in the period divided by those completions plus currently actionable tasks due in the period.',
    plannedTime: 'Planned time',
    plannedTimeBasis: 'Duration of non-cancelled plan blocks in the selected period.',
    completedBlockTime: 'Completed plan-block time',
    completedBlockTimeBasis: 'Duration of blocks explicitly marked completed in the selected period.',
    overCapacityDays: 'Days over capacity',
    overCapacityBasis: 'Days whose planned minutes exceed the configured daily planning capacity.',
    overlaps: 'Overlapping block pairs',
    overlapBasis: 'Pairs of non-cancelled blocks whose local scheduled times overlap.',
    routineOutcomes: 'Routine completed / skipped / pending',
    routineOutcomesBasis: 'Outcomes and open opportunities from current active routine schedules.',
    milestonesCompleted: 'Milestones completed',
    milestonesBasis: 'Milestones with a completion timestamp inside the selected period.',
    activeGoals: 'Active goals',
    activeGoalsBasis: 'Current non-deleted goals marked active.',
    reflectionCount: 'Reflections',
    reflectionCountBasis: 'Daily, weekly, and goal reflections whose period starts in this range.',
    explanations: 'What the records show',
    explanationBasis: 'Rule-based statements from the metrics above, shown in a stable order with at most four items.',
    explainOverCapacity: 'You planned more time than your selected capacity on {{count}} days.',
    explainOverlap: '{{count}} overlapping schedule pairs are present in this period.',
    explainHighPriority: '{{count}} high-priority tasks remain.',
    explainRoutineMore: 'Routine check-ins were more than in the previous period.',
    explainRoutineSimilar: 'Routine check-ins were similar to the previous period.',
    explainRoutineLess: 'Routine check-ins were fewer than in the previous period.',
    explainInsufficient: 'There is not enough recorded activity yet to describe a comparison pattern.',
    workload: 'Workload signals',
    blockCompletion: '{{completed}} of {{total}} planned blocks are marked completed.',
    unscheduledTasksValue: '{{count}} actionable tasks have no non-cancelled plan block.',
    overlapCounting: 'Overlapping block durations are counted separately in planned time.',
    dayWorkload: 'Days with planned time in this period',
    dayWorkloadValue: '{{planned}} planned; capacity {{capacity}}.',
    noPlannedTime: 'No planned time is recorded in this period.',
    weekdayDistribution: 'Weekday workload distribution',
    taskPatterns: 'Task patterns',
    overdueValue: '{{count}} actionable tasks are overdue.',
    pendingValue: '{{count}} tasks are pending.',
    inProgressValue: '{{count}} tasks are in progress.',
    activeGoalTasksValue: '{{count}} actionable tasks connect to active goals.',
    completedByPriority: 'Completed tasks by priority',
    completedByDay: 'Completed tasks by day',
    completedDayValue: '{{count}} tasks completed.',
    noCompletedTasks: 'No task completion timestamps fall in this period.',
    routineSummary: 'Routine summary',
    routineCompletedValue: '{{count}} completed check-ins.',
    routineSkippedValue: '{{count}} skipped check-ins.',
    routinePendingValue: '{{count}} scheduled opportunities have no check-in.',
    routineOpportunityValue: '{{count}} scheduled opportunities from current active schedules.',
    routineCompletionRatio: 'Completion ratio: {{completed}}/{{scheduled}} scheduled opportunities.',
    routineBasis: 'Current schedules are applied consistently to both periods. Historical schedule edits are not inferred.',
    routineItemValue: '{{completed}} completed, {{skipped}} skipped, {{pending}} pending, {{scheduled}} scheduled.',
    goalContext: 'Goal context',
    linkedTasksCompletedValue: '{{count}} goal-linked tasks were completed in this period.',
    upcomingTargetsValue: '{{count}} active goals have an upcoming target within this range length.',
    noNextActionValue: '{{count}} active goals do not have an actionable selected next action.',
    goalReflectionsValue: '{{count}} goal reflections start in this period.',
    goalProgressBasis: 'Goal progress uses the established method selected on each goal.',
    trendBasis: 'Each value is compared with the immediately preceding period of the same calendar-day length. A pattern requires at least two recorded observations.',
    directionMore: 'More than the previous period',
    directionSimilar: 'Similar to the previous period',
    directionLess: 'Less than the previous period',
    directionInsufficient: 'Not enough data to compare',
    exactComparison: 'Current: {{current}}. Previous: {{previous}}.',
    absoluteDifference: 'Absolute difference: {{difference}}.',
    percentageDifference: '{{percentage}} relative to the previous value.',
    minimumSample: 'At least {{count}} recorded observations are required.',
    trendTasks: 'Tasks completed',
    trendPlanned: 'Planned workload',
    trendCapacity: 'Over-capacity days',
    trendRoutines: 'Routine check-ins',
    trendMilestones: 'Milestone completions',
    trendReflections: 'Reflection activity',
  },
  reflections: {
    create: 'Create reflection',
    edit: 'Edit reflection',
    daily: 'Daily reflection',
    weekly: 'Weekly reflection',
    goal: 'Goal reflection',
    newDaily: 'Reflect on today',
    newWeekly: 'Reflect on this week',
    reflectToday: 'Reflect on today',
    reflectGoal: 'Reflect on this goal',
    history: 'Reflection history',
    emptyTitle: 'No reflections yet',
    empty: 'Daily, weekly, and goal reflections will stay available here.',
    optionalQuestions: 'Optional questions',
    questionImportant: 'What felt important today?',
    questionHelped: 'What helped your plan?',
    questionAdjust: 'What would you adjust?',
    questionNextWeek: 'What deserves attention next week?',
    questionGoalProgress: 'What progress matters for this goal?',
    questionGoalNext: 'What would be a useful next step?',
    body: 'Reflection',
    bodyHint: 'Required. Leading and trailing whitespace is removed. Use {{count}} characters or fewer.',
    mood: 'Optional mood',
    moodLow: 'Low',
    moodSteady: 'Steady',
    moodGood: 'Good',
    moodGreat: 'Great',
    moodValue: 'Mood: {{mood}}',
    moodLimit: 'Mood is an optional label only. It is not inferred or converted into a score.',
    delete: 'Delete reflection',
    deleteTitle: 'Delete this reflection?',
    deleteDescription: 'The reflection will leave your history. Other planning records are unchanged.',
    unavailable: 'Reflection not available',
    unavailableDescription: 'It may have been removed or changed. Return to Insights and refresh.',
  },
  reminders: {
    title: 'Reminder',
    manage: 'Manage reminder',
    unavailable: 'Reminder unavailable',
    unavailableDescription: 'This planning item is missing, removed, or outside the active workspace.',
    permissionExplanation: 'Reminders stay on this device. Permission is requested only when you choose to allow a reminder.',
    permissionStatus: 'Notification permission',
    permissionUndetermined: 'Not requested',
    permissionAllowed: 'Allowed',
    permissionDenied: 'Denied for now',
    permissionBlocked: 'Blocked in device settings',
    permissionUnavailable: 'Unavailable on this platform',
    allow: 'Allow reminders',
    openSettings: 'Open device settings',
    enabled: 'Reminder enabled',
    deliveryNote: 'The operating system controls delivery timing, so an exact time is not promised.',
    timing: 'Reminder timing',
    relative: 'Before the planned time',
    absolute: 'Specific date and time',
    offset: 'How early',
    atTime: 'At the time',
    before15: '15 minutes before',
    before60: '1 hour before',
    beforeDay: '1 day before',
    date: 'Reminder date',
    time: 'Reminder time',
    upcoming: 'Upcoming reminder status',
    reasonQuiet_hours_stale: 'Skipped because quiet-hour deferral would be too late.',
    reasonSchedule_failed: 'Scheduling needs another try.',
    reasonCancel_failed: 'A previous device schedule could not be cleared yet.',
    genericTitle: 'Planora reminder',
    genericBody: 'Open Planora to review what you planned.',
    fallbackTitle: 'This reminder cannot open that item',
    fallbackMissing: 'The item may have been removed or may belong to another workspace. Your local data is unchanged.',
    fallbackMalformed: 'The reminder destination was not valid. Planora opened this safe page instead.',
    settingsTitle: 'Reminders and quiet hours',
    showTitles: 'Show planning titles in notifications',
    showTitlesDescription: 'Off by default. Generic notification text keeps lock-screen details private.',
    quietHours: 'Use quiet hours',
    quietHoursDescription: 'Reminders inside quiet hours move to the end when still useful; stale occurrences are skipped.',
    quietStart: 'Quiet hours start',
    quietEnd: 'Quiet hours end',
    settingsSaved: 'Reminder preferences saved locally.',
    reconcile: 'Reconcile device schedules',
    reconcileResult: '{{scheduled}} scheduled, {{skipped}} skipped, {{errors}} need attention.',
  },
  calendar: {
    title: 'Device calendar',
    explanation: 'Optionally export Planora plan blocks one way to a writable device calendar. Planora never imports unrelated events.',
    mobileOnly: 'Device calendar export is available on Android and iOS. Your Planora plan remains available on web.',
    choose: 'Choose writable calendar',
    selected: 'Selected calendar: {{name}}',
    noneSelected: 'No destination calendar selected',
    noWritable: 'No writable calendars are available.',
    disconnect: 'Forget selected calendar',
    exportTitle: 'Device calendar export',
    exportDescription: 'Only this plan block is exported. External changes are never overwritten without your decision.',
    chooseInSettings: 'Choose a writable calendar in Settings before exporting.',
    export: 'Export plan block',
    updateExport: 'Check and update export',
    removeExport: 'Remove calendar mapping',
    removeTitle: 'Remove this calendar export?',
    removeDescription: 'Choose whether to keep the device calendar event or remove both the event and Planora mapping.',
    keepExternal: 'Keep calendar event',
    removeBoth: 'Remove both',
    missingConflict: 'The mapped calendar event was not found. You can create a new event explicitly.',
    changedConflict: 'The calendar event changed outside Planora. Review it before choosing whether to replace it.',
    createAgain: 'Create a new event',
    replaceExternal: 'Replace with Planora details',
  },
  sync: {
    eyebrow: 'PRIVACY AND DATA',
    title: 'Privacy and data',
    description: 'Export or remove your data, and optionally synchronize planning records after a clear, explicit choice.',
    settingsTitle: 'Privacy and data',
    settingsDescription: 'Manage local data, portable export, optional synchronization, and account deletion.',
    manage: 'Manage privacy and data',
    localOnly: 'Local-only mode',
    enabled: 'Synchronization enabled',
    localFirst: 'SQLite remains the immediate source of truth. Normal planning never waits for the network.',
    status: 'Synchronization status',
    stateLocal: 'Local-only. Nothing is uploaded.',
    stateIdle: 'Up to date after the last completed check.',
    stateSyncing: 'Synchronizing a bounded batch.',
    stateOffline: 'Offline. Pending changes remain safely queued.',
    stateError: 'Synchronization needs another attempt. Local planning remains available.',
    stateConflict: 'One or more changes need your choice.',
    stateRestoring: 'Restoring a bounded batch into local storage.',
    stateAccountMismatch: 'Synchronization stopped because a different account is signed in.',
    pendingCount: '{{count}} queued local changes',
    lastSuccess: 'Last completed check: {{value}}',
    recoverableError: 'The remote request did not complete. Local data was not discarded.',
    syncNow: 'Synchronize now',
    disable: 'Disable synchronization',
    upload: 'Upload this device',
    merge: 'Merge with cloud workspace',
    restore: 'Restore cloud workspace',
    activationNote: 'Signing in never enables this automatically. Upload keeps this device as the starting point; merge preserves local records; restore downloads owned records without inventing history.',
    signInRequired: 'Sign in first, then return here to make an explicit synchronization choice.',
    unavailable: 'Remote account services are not configured. Local-only planning remains fully available.',
    reviewConflicts: 'Review conflicts ({{count}})',
    conflictEyebrow: 'YOUR CHOICE',
    conflictTitle: 'Resolve synchronized changes',
    conflictDescription: 'Both versions are preserved until you deliberately choose what to keep.',
    conflictItem: '{{type}} change',
    conflictBasis: 'Local revision {{local}} and cloud revision {{remote}} changed independently.',
    keepLocal: 'Keep local version',
    keepCloud: 'Keep cloud version',
    combineText: 'Combine supported text',
    noConflicts: 'No changes currently need resolution.',
    exportTitle: 'Portable export',
    exportDescription: 'Create a versioned JSON copy of planning data without credentials, native notification identifiers, or device calendar identifiers.',
    exportAction: 'Export planning data',
    exportDialog: 'Export Planora planning data',
    deletionTitle: 'Removal controls',
    deletionDescription: 'These actions are separate. A failed remote action is never reported as completed.',
    clearDevice: 'Clear planning data from this device',
    deleteCloud: 'Delete synchronized cloud planning data',
    deleteAccount: 'Delete Planora account',
    confirmTitle: 'Type the confirmation phrase',
    confirmClear: 'Type CLEAR. This removes planning records from this device. It does not delete cloud data or the account.',
    confirmCloud: 'Type DELETE CLOUD. This removes synchronized planning records from the account but keeps the account and device data.',
    confirmAccount: 'Type DELETE ACCOUNT. The server must delete the signed-in account. Device planning data remains until separately cleared.',
    confirmation: 'Confirmation phrase',
    completedTitle: 'Action completed',
    deviceCleared: 'Planning data was cleared from this device.',
    cloudDeleted: 'Synchronized cloud planning data was deleted.',
    accountDeleted: 'The account deletion request completed. Device data was not automatically removed.',
  },
  entityTypes: {
    workspace: 'workspace',
    task: 'task',
    planBlockSeries: 'repeating plan',
    planBlock: 'plan block',
    routine: 'routine',
    routineCheckIn: 'routine check-in',
    goal: 'goal',
    milestone: 'milestone',
    goalRoutineLink: 'goal and routine link',
    area: 'area',
    tag: 'tag',
    reflection: 'reflection',
    appSettings: 'planning preferences',
    reminderIntent: 'reminder choice',
  },
  recoveryBoundary: {
    title: 'This area needs another try',
    description: 'Your saved local data is unchanged. Try opening this area again or return to Today.',
    retry: 'Try this area again',
    retryHint: 'Restarts only this area without clearing local data.',
    today: 'Return to Today',
    todayHint: 'Leaves this area and opens Today.',
  },
  notFound: {
    eyebrow: 'SAFE RETURN',
    title: 'That destination is not available',
    description: 'The link may be incomplete or no longer point to an available record. Your saved data is unchanged.',
    today: 'Open Today',
  },
  destructive: {
    clearDevice: 'Clear device data',
    deleteCloud: 'Delete cloud data',
    deleteAccount: 'Delete account',
    calendarStateHint: 'Choose whether linked device calendar events are also removed.',
  },
  nativePermissions: {
    reminderChannel: 'Planora reminders',
    reminderChannelDescription: 'Reminders you explicitly choose in Planora',
  },
  settings: {
    eyebrow: 'YOUR SPACE',
    title: 'Settings',
    description: 'Personalize how Planora looks and behaves, with accessible defaults from the start.',
    language: 'Language',
    languageDescription: 'Choose the interface language for this local profile.',
    systemLanguage: 'Use device language',
    directionRestart: 'Restart Planora to apply right-to-left layout throughout the native app. Expo Go may reset this preference; use a development build for native RTL verification.',
    planning: 'Planning preferences',
    planningDescription: 'Set a calm daily capacity for workload comparisons.',
    capacity: 'Daily capacity in minutes',
    capacityHint: 'Choose between 30 and 1,440 minutes.',
    saveCapacity: 'Save capacity',
    saved: 'Preference saved.',
  },
  storage: {
    title: 'Data and storage',
    description: 'Your planning foundation lives locally on this device.',
    localData: 'Local data',
    localReady: 'Available on this device',
    localPreparing: 'Preparing availability',
    offline: 'Offline readiness',
    offlineReady: 'Ready for offline use',
    offlinePreparing: 'Finishing setup',
    state: 'Storage state',
    ready: 'Ready',
    preparing: 'Preparing',
    errorTitle: 'Local storage needs another try',
    retryLabel: 'Try preparing local storage again',
  },
  validation: {
    reflectionBody: 'Write a reflection before saving.',
    reflectionLength: 'Use 8,000 characters or fewer.',
    reflectionDate: 'Choose a valid reflection date.',
    reflectionScope: 'This reflection scope does not use an identifier.',
    reflectionMood: 'Choose an available mood label.',
    reflectionDuplicate: 'A reflection already exists for this period.',
    taskTitle: 'Enter a task title.',
    blockTitle: 'Enter a block title.',
    routineTitle: 'Enter a routine title.',
    goalTitle: 'Enter a goal title.',
    milestoneTitle: 'Enter a milestone title.',
    percentage: 'Enter a whole percentage from 0 through 100.',
    activeArea: 'Choose an active area from this workspace.',
    availableGoal: 'Choose an available goal from this workspace.',
    titleLength: 'Use 200 characters or fewer.',
    notesLength: 'Use 4,000 characters or fewer.',
    date: 'Use a valid date in YYYY-MM-DD format.',
    startDate: 'Use a valid start date.',
    endDate: 'Use a valid end date.',
    time: 'Use a valid time in HH:MM format.',
    startTime: 'Use a valid start time in HH:MM format.',
    endTime: 'Use a valid end time in HH:MM format.',
    endAfterStart: 'End time must be after start time.',
    nonexistentTime: 'Choose a local time that exists on this date.',
    scheduledNeedsDate: 'Choose a due date for a scheduled time.',
    weekdays: 'Choose at least one weekday.',
    interval: 'Repeat interval must be between 1 and 365.',
    capacity: 'Choose a whole number from 30 to 1,440.',
    emailRequired: 'Enter your email address.',
    emailComplete: 'Enter a complete email address.',
    passwordRequired: 'Enter your password.',
    passwordLength: 'Use at least eight characters.',
    displayNameRequired: 'Enter a display name.',
    displayNameLength: 'Use 60 characters or fewer.',
    passwordsMatch: 'Passwords do not match.',
  },
  errors: {
    insightsRefresh: 'Planora could not refresh insights. Saved local data is unchanged.',
    reflectionRevision: 'This reflection changed before your update was saved. Refresh and try again.',
    reflectionSave: 'That reflection change could not be saved. Refresh and try again.',
    reflectionUnavailable: 'The reflection is no longer available.',
    refreshDay: 'Planora could not refresh this day. Your saved local data is unchanged.',
    revision: 'This item changed before your update was saved. Refresh and try again.',
    save: 'That change could not be saved. Refresh and try again.',
    onboardingRead: 'Planora could not read onboarding preferences. Your local data is still available.',
    onboardingSave: 'Planora could not save this preference. Please try again.',
    workspace: 'Planora could not prepare your local planning space. Your data has not been changed.',
    generic: 'Wait a moment and try again.',
    invalidCredentials: 'The email or password was not accepted. Check both and try again.',
    emailUnverified: 'Confirm your email before signing in, then try again.',
    emailInUse: 'This email cannot be used for a new account. Try signing in instead.',
    weakPassword: 'Choose a stronger password with at least eight characters.',
    networkUnavailable: 'Planora could not reach the account service. Check your connection and try again.',
    rateLimited: 'Too many attempts were made. Wait a moment, then try again.',
    expiredLink: 'This recovery link is no longer valid. Request a new link and try again.',
    serviceUnavailable: 'Account services are temporarily unavailable. Your local data is unaffected.',
    accountUnknown: 'Something went wrong with the account request. Your local data is unaffected.',
    linkTask: 'Choose an available task from this workspace.',
    linkRoutine: 'Choose an available routine from this workspace.',
    linkEither: 'Link either a task or a routine, not both.',
    endBeforeStart: 'End date cannot be before the start date.',
    recurrenceConflict: 'This recurrence changed. Refresh and try again.',
    recurrenceWindow: 'Recurrence windows are limited to 56 days.',
    scheduleRefresh: 'Your schedule could not be refreshed. Saved local data is unchanged.',
    scheduleRevision: 'This schedule changed before your update was saved. Refresh and try again.',
    scheduleSave: 'That schedule change could not be saved. Refresh and try again.',
    goalsRefresh: 'Planora could not refresh goals. Saved local data is unchanged.',
    goalRevision: 'This goal changed before your update was saved. Refresh and try again.',
    goalSave: 'That goal change could not be saved. Refresh and try again.',
    goalUnavailable: 'The goal is no longer available.',
    goalTaskActionable: 'Only actionable tasks can be linked.',
    goalTaskOwned: 'This task already supports another goal.',
    goalTaskMissing: 'This task is not linked to the goal.',
    goalNextAction: 'Choose an actionable task linked to this goal.',
    goalRoutineActive: 'Choose an active routine from this workspace.',
  },
  placeholders: {
    goalsDescription: 'Turn longer-term intentions into visible milestones and practical next actions.',
    goalsEmpty: 'Meaningful progress starts here',
    goalsEmptyDescription: 'Goal paths, milestones, and progress check-ins are planned for a dedicated feature phase.',
    insightsDescription: 'Notice helpful patterns while keeping personal data understandable and private.',
    insightsEmpty: 'Your patterns will tell a story',
    insightsEmptyDescription: 'Trends and reflections will appear once there is meaningful activity to summarize.',
  },
} as const;

type DeepStringShape<T> = {
  [Key in keyof T]: T[Key] extends string ? string : DeepStringShape<T[Key]>;
};

export type TranslationCatalog = DeepStringShape<typeof en>;

export type TranslationKey = {
  [Section in keyof typeof en]: {
    [Key in keyof (typeof en)[Section]]: `${Section & string}.${Key & string}`;
  }[keyof (typeof en)[Section]];
}[keyof typeof en];
