export const en = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    continue: 'Continue',
    create: 'Create',
    delete: 'Delete',
    done: 'Done',
    edit: 'Edit',
    goBack: 'Go back',
    keep: 'Keep',
    loading: 'Loading',
    noNotes: 'No notes',
    none: 'None',
    refresh: 'Refresh',
    retry: 'Try again',
    save: 'Save',
    skip: 'Skip',
    today: 'Today',
    tomorrow: 'Tomorrow',
    yesterday: 'Yesterday',
    active: 'Active',
    paused: 'Paused',
    archived: 'Archived',
    planned: 'Planned',
    completed: 'Completed',
    cancelled: 'Cancelled',
    pending: 'Pending',
    inProgress: 'In progress',
    skipped: 'Skipped',
    anyTime: 'Any time today',
    minuteOne: '{{count}} minute',
    minuteOther: '{{count}} minutes',
    hourOne: '{{count}} hour',
    hourOther: '{{count}} hours',
  },
  launch: {
    starting: 'Planora is starting',
    tagline: 'Make space for what matters.',
    storage: 'Preparing local storage.',
    account: 'Restoring your account.',
    preferences: 'Loading your preferences.',
    workspace: 'Preparing your planning space.',
  },
  tabs: {
    today: 'Today',
    planner: 'Planner',
    goals: 'Goals',
    insights: 'Insights',
    settings: 'Settings',
  },
  auth: {
    chooseTitle: 'Choose what fits today',
    chooseDescription: 'Keep using Planora locally, or add an account for a small profile and account recovery. Planning content stays on this device.',
    localTitle: 'Continue locally',
    localDescription: 'No account is required. Your existing local planning data remains ready offline.',
    accountTitle: 'Optional account',
    accountDescription: 'Create a profile or sign in. This does not upload, merge, or replace local planning records.',
    accountUnavailable: 'Account services are not configured in this build. Local-only use remains available.',
    createAccount: 'Create account',
    signIn: 'Sign in',
    signInTitle: 'Welcome back',
    signInDescription: 'Sign in to your optional Planora account. Your local planning space remains separate and available.',
    createTitle: 'Create your account',
    createDescription: 'Create a minimal account profile for sign-in and recovery. Planning content is not sent to the account service.',
    displayName: 'Display name',
    displayNamePlaceholder: 'How you want to be addressed',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    confirmPassword: 'Confirm password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    alreadyAccount: 'Already have an account? Sign in',
    createInstead: 'Create an account',
    forgotPassword: 'Forgot password?',
    recoveryEyebrow: 'ACCOUNT RECOVERY',
    recoveryTitle: 'Reset your password',
    recoveryDescription: 'Enter your email and we will request a recovery message without revealing whether an account exists.',
    sendRecovery: 'Send recovery instructions',
    secureRecovery: 'SECURE RECOVERY',
    choosePassword: 'Choose a new password',
    choosePasswordDescription: 'Choose a new password for your account. This does not change or remove local planning data.',
    savePassword: 'Save new password',
    checkEmailEyebrow: 'CHECK YOUR EMAIL',
    checkEmailTitle: 'One more step',
    checkEmailDescription: 'If the address can receive the requested message, follow the link in that message to continue.',
    inboxTitle: 'The next step happens in your inbox',
    returnSignIn: 'Return to sign in',
    recoveryValidating: 'Planora is validating the recovery link without showing its private session details.',
    requestNewLink: 'Request a new link',
    issueEyebrow: 'RECOVERABLE ISSUE',
    issueTitle: "Let's try another path",
    issueDescription: 'The account request did not complete, but your local Planora data is safe and remains available.',
    accountOptions: 'Back to account options',
    profileEyebrow: 'ACCOUNT PROFILE',
    editProfile: 'Edit profile',
    profileDescription: 'This small account profile is separate from your local planning records.',
    profileScope: 'Profile scope',
    saveProfile: 'Save profile',
    signOut: 'Sign out',
    signOutTitle: 'Sign out of your account?',
    signOutDescription: 'Your planning data stays on this device and remains available after sign-out.',
    accountLabel: 'Account',
    accountSettingsDescription: 'Account features are optional and stay separate from local planning data.',
    planoraAccount: 'Planora account',
    localOnly: 'Local-only',
    localOnlyDescription: 'No account is required to use the main planning tabs.',
    emailVerified: 'Email verified',
    emailPending: 'Email verification pending',
    viewOnboarding: 'View onboarding again',
    newToAccount: 'New to account features?',
    passwordPrivacy: 'Your password is sent securely to the account provider and is never stored in Planora\'s local planning database.',
    recoveryPrivacy: 'For privacy, the confirmation screen is the same for every valid email format.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
  onboarding: {
    pageOneEyebrow: 'A CALMER START',
    pageOneTitle: 'Your day, with room to breathe',
    pageOneDescription: 'Planora brings tasks and routines into a quiet daily view while keeping the rest of your planning spaces close.',
    pageOneDetail: 'Capture tasks and check in with routines without creating an account.',
    pageTwoEyebrow: 'LOCAL BY DEFAULT',
    pageTwoTitle: 'Ready when the network is not',
    pageTwoDescription: 'Your planning foundation is stored on this device and remains available offline. Local actions never wait for an account service.',
    pageTwoDetail: 'Local data survives app restarts and stays separate from account sessions.',
    pageThreeEyebrow: 'YOUR CHOICE',
    pageThreeTitle: 'An account is optional',
    pageThreeDescription: 'Create an account for profile and recovery access, or continue locally. Planning content is not uploaded or synchronized.',
    pageThreeDetail: 'You can sign in later from Settings without changing local identifiers.',
    close: 'Close onboarding',
    skip: 'Skip onboarding',
    step: 'Step {{current}} of {{total}}',
    stepAnnouncement: 'Step {{current}} of {{total}}. {{title}}',
    startLocally: 'Start locally',
  },
  today: {
    greeting: 'A clear view of today',
    subtitle: 'Choose what matters, then leave room for the day to move.',
    quickPlaceholder: 'Add a task for today',
    quickLabel: 'Quick add task',
    quickHint: 'Creates a task due today',
    add: 'Add',
    progress: '{{completed}} of {{total}} complete',
    workload: '{{planned}} planned · {{remaining}} remaining',
    nextUp: 'Next up',
    priority: 'Priority and overdue',
    remaining: "Today's tasks",
    routines: 'Scheduled routines',
    agenda: 'Agenda preview',
    completed: 'Completed',
    showCompleted: 'Show completed items',
    hideCompleted: 'Hide completed items',
    quietEmpty: 'Nothing needs your attention yet.',
    noPriority: 'No priority or overdue tasks.',
    noRemaining: 'No remaining tasks for today.',
    noRoutines: 'No routines are scheduled today.',
    noAgenda: 'No time blocks are planned yet.',
    allTasks: 'All tasks',
    allRoutines: 'Routines',
    openPlanner: 'Open Planner',
    moreActions: 'More actions',
    loading: 'Loading your day.',
    refreshTitle: 'Your day needs a refresh',
    failed: 'Your day could not be loaded.',
    completedToday: 'Completed today',
    skippedToday: 'Skipped today',
    markComplete: 'Mark complete',
    markSkipped: 'Mark skipped',
    undo: 'Undo check-in',
    overdue: 'Overdue',
    dueToday: 'Due today',
    unscheduled: 'Inbox',
  },
  tasks: {
    title: 'All tasks',
    new: 'New task',
    details: 'Task details',
    createDescription: 'Add what matters, then shape its timing only if helpful.',
    editDescription: 'Update the task without changing its stable local identity.',
    loading: 'Loading task details.',
    refreshTitle: 'Task details need a refresh',
    listRefresh: 'Your task list needs a refresh',
    notLoaded: 'The task could not be loaded.',
    unavailable: 'Task not available',
    unavailableDescription: 'It may have been removed or changed. Return to Today and refresh.',
    emptyTitle: 'No tasks yet',
    emptyDescription: 'Quick captures and full tasks will stay available here.',
    createAction: 'Create a task',
    actions: 'Task actions',
    complete: 'Complete task',
    reopen: 'Reopen task',
    cancel: 'Cancel task',
    delete: 'Delete task',
    cancelTitle: 'Cancel task?',
    cancelDescription: 'The task will move out of active daily sections and can be reopened later.',
    keep: 'Keep task',
    deleteTitle: 'Delete task?',
    deleteDescription: 'This removes the task from your daily views. This action cannot be undone here.',
    overdue: 'Overdue',
    upcoming: 'Upcoming',
    unscheduled: 'Unscheduled',
    opensDetails: 'Opens task details',
    titleField: 'Title',
    notesField: 'Notes',
    priorityField: 'Priority',
    statusField: 'Status',
    dueDate: 'Due date',
    dueDateHint: 'Use YYYY-MM-DD, or leave blank.',
    scheduledTime: 'Scheduled time',
    timeHint: 'Use 24-hour HH:MM, or leave blank.',
    priorityNone: 'No priority',
    priorityLow: 'Low priority',
    priorityMedium: 'Medium priority',
    priorityHigh: 'High priority',
  },
  routines: {
    title: 'Routines',
    new: 'New routine',
    details: 'Routine details',
    description: 'Build a light daily or weekly rhythm without reminders or scoring.',
    loading: 'Loading routine details.',
    refreshTitle: 'Routine details need a refresh',
    listRefresh: 'Your routine list needs a refresh',
    notLoaded: 'The routine could not be loaded.',
    unavailable: 'Routine not available',
    unavailableDescription: 'Return to Today and refresh your local planning data.',
    emptyTitle: 'No routines yet',
    emptyDescription: 'Create a daily rhythm or choose the weekdays that fit.',
    createAction: 'Create a routine',
    opensDetails: 'Opens routine details',
    schedule: 'Schedule',
    everyDay: 'Every day',
    selectedDays: 'Selected days',
    weekdays: 'Weekdays',
    preferredTime: 'Preferred time',
    state: 'Routine state',
  },
  planner: {
    title: 'Planner',
    day: 'Day',
    week: 'Week',
    previousDay: 'Previous day',
    nextDay: 'Next day',
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    currentWeek: 'Current week',
    date: 'Date',
    timeline: 'Daily timeline',
    newBlock: 'New time block',
    editBlock: 'Edit time block',
    blockDetails: 'Time block details',
    unscheduledTasks: 'Unscheduled tasks',
    scheduleTask: 'Schedule task',
    noBlocks: 'No time blocks are planned for this day.',
    noTasks: 'All actionable tasks have a time block.',
    workload: 'Workload',
    plannedMinutes: '{{duration}} planned',
    remainingCapacity: '{{duration}} remaining',
    overCapacity: '{{duration}} beyond your daily capacity',
    withinCapacity: 'Within your daily capacity',
    overlapOne: '{{count}} overlap',
    overlapOther: '{{count}} overlaps',
    unscheduledOne: '{{count}} unscheduled task',
    unscheduledOther: '{{count}} unscheduled tasks',
    blockOne: '{{count}} block',
    blockOther: '{{count}} blocks',
    taskOne: '{{count}} task',
    taskOther: '{{count}} tasks',
    overlapWarning: 'This block overlaps another block. You can keep it or change the time.',
    overlapCounted: 'Overlapping blocks are counted separately in planned time.',
    overloaded: 'Over capacity',
    linkedTask: 'Linked task',
    linkedRoutine: 'Linked routine',
    removeLink: 'Remove link',
    completeBlock: 'Complete block',
    reopenBlock: 'Reopen block',
    cancelBlock: 'Cancel block',
    deleteBlock: 'Delete block',
    deleteTitle: 'Delete time block?',
    deleteDescription: 'This removes only this scheduled block. Linked tasks and routines remain available.',
    cancelTitle: 'Cancel time block?',
    cancelDescription: 'Cancelled blocks stay in history and stop counting toward capacity.',
    keepBlock: 'Keep block',
    startTime: 'Start time',
    endTime: 'End time',
    titleField: 'Title',
    notesField: 'Notes',
    statusField: 'Status',
    repeat: 'Repeat',
    repeatNone: 'Does not repeat',
    repeatDaily: 'Daily',
    repeatWeekly: 'Weekly',
    repeatInterval: 'Repeat interval',
    repeatEnd: 'Repeat end date',
    editOccurrence: 'Edit this occurrence',
    editFuture: 'Edit this and future occurrences',
    recurrenceBounded: 'Occurrences are prepared in a rolling eight-week window.',
    move: 'Move or reschedule',
    selectedDay: 'Selected day',
    currentTime: 'Current time',
    capacitySummary: '{{planned}} planned out of {{capacity}} capacity',
    loading: 'Loading your schedule.',
    refreshTitle: 'Your schedule needs a refresh',
  },
  goals: {
    heading: 'Goals',
    summaryActive: '{{count}} active',
    create: 'Create goal',
    edit: 'Edit goal',
    details: 'Goal details',
    formDescription: 'Shape a clear direction without turning it into a scorecard.',
    titleField: 'Title',
    descriptionField: 'Description',
    motivationField: 'Why this matters',
    area: 'Area',
    horizon: 'Horizon',
    horizonMonth: 'Month',
    horizonQuarter: 'Quarter',
    horizonYear: 'Year',
    horizonSomeday: 'Someday',
    targetDate: 'Target date',
    targetDateHint: 'Use YYYY-MM-DD, or leave blank.',
    status: 'Status',
    statusActive: 'Active',
    statusPaused: 'Paused',
    statusCompleted: 'Completed',
    statusAbandoned: 'Abandoned',
    progressMethod: 'Progress method',
    progressMilestones: 'Milestones',
    progressTasks: 'Linked tasks',
    progressManual: 'Manual percentage',
    progressNone: 'No numeric progress',
    manualProgress: 'Manual progress',
    manualHint: 'Enter a whole percentage from 0 through 100.',
    loading: 'Loading goals.',
    refreshTitle: 'Goals need a refresh',
    notLoaded: 'Goals could not be loaded. Your saved data is unchanged.',
    unavailable: 'Goal not available',
    unavailableDescription: 'It may have been removed or changed. Return to Goals and refresh.',
    emptyTitle: 'Make room for one meaningful direction',
    emptyDescription: 'Create a goal when a longer path would benefit from a calm next step.',
    search: 'Search goals',
    noMatches: 'No goals match this search or filter.',
    filterCurrent: 'Current',
    filterCompleted: 'Completed',
    filterAll: 'All',
    activeGoals: 'Active goals',
    pausedGoals: 'Paused goals',
    completedGoals: 'Completed goals',
    somedayGoals: 'Someday goals',
    abandonedGoals: 'Abandoned goals',
    noTargetDate: 'No target date',
    targetContext: 'Target {{date}}',
    nextMilestone: 'Next milestone',
    nextAction: 'Next action',
    notStarted: 'Not started',
    progressCount: '{{completed}} of {{total}} complete',
    percentComplete: '{{percent}} complete',
    noNumericProgress: 'Progress follows the next useful step.',
    opensDetails: 'Opens goal details',
    motivation: 'Why it matters',
    milestones: 'Milestones',
    linkedTasks: 'Linked next actions',
    supportingRoutines: 'Supporting routines',
    addMilestone: 'Add milestone',
    linkTask: 'Link task',
    linkRoutine: 'Link routine',
    createTask: 'Create task for goal',
    noMilestones: 'No milestones yet.',
    noTasks: 'No tasks are linked.',
    noRoutines: 'No routines support this goal yet.',
    milestoneTitle: 'Milestone title',
    milestoneNotes: 'Notes',
    milestoneDate: 'Target date',
    milestonePending: 'Pending',
    milestoneCompleted: 'Completed',
    milestoneCancelled: 'Cancelled',
    newMilestone: 'New milestone',
    editMilestone: 'Edit milestone',
    completeMilestone: 'Complete milestone',
    reopenMilestone: 'Reopen milestone',
    cancelMilestone: 'Cancel milestone',
    deleteMilestone: 'Delete milestone',
    moveUp: 'Move up',
    moveDown: 'Move down',
    moveUpHint: 'Moves this milestone earlier in the goal.',
    moveDownHint: 'Moves this milestone later in the goal.',
    setNextAction: 'Set as next action',
    clearNextAction: 'Clear next action',
    unlinkTask: 'Unlink task',
    unlinkRoutine: 'Unlink routine',
    routineCompletedToday: 'Completed today',
    routineSkippedToday: 'Skipped today',
    routinePendingToday: 'Pending today',
    actions: 'Goal actions',
    pause: 'Pause goal',
    resume: 'Resume goal',
    complete: 'Complete goal',
    reopen: 'Reopen goal',
    abandon: 'Abandon goal',
    delete: 'Delete goal',
    pauseTitle: 'Pause this goal?',
    pauseDescription: 'The goal will stay available without appearing as active.',
    completeTitle: 'Complete this goal?',
    completeDescription: 'This records completion without changing linked tasks or routines.',
    abandonTitle: 'Abandon this goal?',
    abandonDescription: 'The goal will leave current sections while its related records remain intact.',
    deleteTitle: 'Delete this goal?',
    deleteDescription: 'The goal leaves your views. Linked tasks and routines remain available.',
    deleteMilestoneTitle: 'Delete this milestone?',
    deleteMilestoneDescription: 'This removes the milestone from the goal. Other goal records remain intact.',
    keepGoal: 'Keep goal',
    keepMilestone: 'Keep milestone',
    chooseTask: 'Choose a task',
    chooseRoutine: 'Choose a routine',
    availableTasks: 'Available actionable tasks',
    availableRoutines: 'Available active routines',
    noAvailableTasks: 'No unlinked actionable tasks are available.',
    noAvailableRoutines: 'No unlinked active routines are available.',
    completionSuggestion: 'All milestones are complete. Complete the goal when it feels finished.',
    needsAttention: 'Needs attention',
    linkedGoal: 'Goal: {{title}}',
    openGoal: 'Open goal {{title}}',
  },
  settings: {
    eyebrow: 'YOUR SPACE',
    title: 'Settings',
    description: 'Personalize how Planora looks and behaves, with accessible defaults from the start.',
    language: 'Language',
    languageDescription: 'Choose the interface language for this local profile.',
    systemLanguage: 'Use device language',
    directionRestart: 'Restart Planora to apply right-to-left layout throughout the native app. Expo Go may reset this preference; use a development build for native RTL verification.',
    planning: 'Planning preferences',
    planningDescription: 'Set a calm daily capacity for workload comparisons.',
    capacity: 'Daily capacity in minutes',
    capacityHint: 'Choose between 30 and 1,440 minutes.',
    saveCapacity: 'Save capacity',
    saved: 'Preference saved.',
  },
  storage: {
    title: 'Data and storage',
    description: 'Your planning foundation lives locally on this device.',
    localData: 'Local data',
    localReady: 'Available on this device',
    localPreparing: 'Preparing availability',
    offline: 'Offline readiness',
    offlineReady: 'Ready for offline use',
    offlinePreparing: 'Finishing setup',
    state: 'Storage state',
    ready: 'Ready',
    preparing: 'Preparing',
    errorTitle: 'Local storage needs another try',
    retryLabel: 'Try preparing local storage again',
  },
  validation: {
    taskTitle: 'Enter a task title.',
    blockTitle: 'Enter a block title.',
    routineTitle: 'Enter a routine title.',
    goalTitle: 'Enter a goal title.',
    milestoneTitle: 'Enter a milestone title.',
    percentage: 'Enter a whole percentage from 0 through 100.',
    activeArea: 'Choose an active area from this workspace.',
    availableGoal: 'Choose an available goal from this workspace.',
    titleLength: 'Use 200 characters or fewer.',
    notesLength: 'Use 4,000 characters or fewer.',
    date: 'Use a valid date in YYYY-MM-DD format.',
    startDate: 'Use a valid start date.',
    endDate: 'Use a valid end date.',
    time: 'Use a valid time in HH:MM format.',
    startTime: 'Use a valid start time in HH:MM format.',
    endTime: 'Use a valid end time in HH:MM format.',
    endAfterStart: 'End time must be after start time.',
    nonexistentTime: 'Choose a local time that exists on this date.',
    scheduledNeedsDate: 'Choose a due date for a scheduled time.',
    weekdays: 'Choose at least one weekday.',
    interval: 'Repeat interval must be between 1 and 365.',
    capacity: 'Choose a whole number from 30 to 1,440.',
    emailRequired: 'Enter your email address.',
    emailComplete: 'Enter a complete email address.',
    passwordRequired: 'Enter your password.',
    passwordLength: 'Use at least eight characters.',
    displayNameRequired: 'Enter a display name.',
    displayNameLength: 'Use 60 characters or fewer.',
    passwordsMatch: 'Passwords do not match.',
  },
  errors: {
    refreshDay: 'Planora could not refresh this day. Your saved local data is unchanged.',
    revision: 'This item changed before your update was saved. Refresh and try again.',
    save: 'That change could not be saved. Refresh and try again.',
    onboardingRead: 'Planora could not read onboarding preferences. Your local data is still available.',
    onboardingSave: 'Planora could not save this preference. Please try again.',
    workspace: 'Planora could not prepare your local planning space. Your data has not been changed.',
    generic: 'Wait a moment and try again.',
    invalidCredentials: 'The email or password was not accepted. Check both and try again.',
    emailUnverified: 'Confirm your email before signing in, then try again.',
    emailInUse: 'This email cannot be used for a new account. Try signing in instead.',
    weakPassword: 'Choose a stronger password with at least eight characters.',
    networkUnavailable: 'Planora could not reach the account service. Check your connection and try again.',
    rateLimited: 'Too many attempts were made. Wait a moment, then try again.',
    expiredLink: 'This recovery link is no longer valid. Request a new link and try again.',
    serviceUnavailable: 'Account services are temporarily unavailable. Your local data is unaffected.',
    accountUnknown: 'Something went wrong with the account request. Your local data is unaffected.',
    linkTask: 'Choose an available task from this workspace.',
    linkRoutine: 'Choose an available routine from this workspace.',
    linkEither: 'Link either a task or a routine, not both.',
    endBeforeStart: 'End date cannot be before the start date.',
    recurrenceConflict: 'This recurrence changed. Refresh and try again.',
    recurrenceWindow: 'Recurrence windows are limited to 56 days.',
    scheduleRefresh: 'Your schedule could not be refreshed. Saved local data is unchanged.',
    scheduleRevision: 'This schedule changed before your update was saved. Refresh and try again.',
    scheduleSave: 'That schedule change could not be saved. Refresh and try again.',
    goalsRefresh: 'Planora could not refresh goals. Saved local data is unchanged.',
    goalRevision: 'This goal changed before your update was saved. Refresh and try again.',
    goalSave: 'That goal change could not be saved. Refresh and try again.',
    goalUnavailable: 'The goal is no longer available.',
    goalTaskActionable: 'Only actionable tasks can be linked.',
    goalTaskOwned: 'This task already supports another goal.',
    goalTaskMissing: 'This task is not linked to the goal.',
    goalNextAction: 'Choose an actionable task linked to this goal.',
    goalRoutineActive: 'Choose an active routine from this workspace.',
  },
  placeholders: {
    goalsDescription: 'Turn longer-term intentions into visible milestones and practical next actions.',
    goalsEmpty: 'Meaningful progress starts here',
    goalsEmptyDescription: 'Goal paths, milestones, and progress check-ins are planned for a dedicated feature phase.',
    insightsDescription: 'Notice helpful patterns while keeping personal data understandable and private.',
    insightsEmpty: 'Your patterns will tell a story',
    insightsEmptyDescription: 'Trends and reflections will appear once there is meaningful activity to summarize.',
  },
} as const;

type DeepStringShape<T> = {
  [Key in keyof T]: T[Key] extends string ? string : DeepStringShape<T[Key]>;
};

export type TranslationCatalog = DeepStringShape<typeof en>;

export type TranslationKey = {
  [Section in keyof typeof en]: {
    [Key in keyof (typeof en)[Section]]: `${Section & string}.${Key & string}`;
  }[keyof (typeof en)[Section]];
}[keyof typeof en];
