import type { TranslationCatalog } from './catalogs.ts';

export const ar = {
  common: {
    back: 'رجوع', cancel: 'إلغاء', close: 'إغلاق', continue: 'متابعة', create: 'إنشاء', delete: 'حذف', done: 'تم', edit: 'تعديل', goBack: 'الرجوع', keep: 'إبقاء', loading: 'جارٍ التحميل', noNotes: 'لا توجد ملاحظات', none: 'بلا', refresh: 'تحديث', retry: 'إعادة المحاولة', save: 'حفظ', skip: 'تخطي', today: 'اليوم', tomorrow: 'غدًا', yesterday: 'أمس', active: 'نشط', paused: 'متوقف مؤقتًا', archived: 'مؤرشف', planned: 'مخطط', completed: 'مكتمل', cancelled: 'ملغى', pending: 'قيد الانتظار', inProgress: 'قيد التنفيذ', skipped: 'تم التخطي', anyTime: 'في أي وقت اليوم', minuteOne: '{{count}} دقيقة', minuteOther: '{{count}} دقيقة', hourOne: '{{count}} ساعة', hourOther: '{{count}} ساعات',
  },
  launch: { starting: 'يبدأ بلانورا', tagline: 'أفسح مجالًا لما يهم.', storage: 'جارٍ إعداد التخزين المحلي.', account: 'جارٍ استعادة حسابك.', preferences: 'جارٍ تحميل تفضيلاتك.', workspace: 'جارٍ إعداد مساحة التخطيط.' },
  tabs: { today: 'اليوم', planner: 'المخطط', goals: 'الأهداف', insights: 'الرؤى', settings: 'الإعدادات' },
  auth: {
    chooseTitle: 'اختر ما يناسب يومك', chooseDescription: 'واصل استخدام بلانورا محليًا، أو أضف حسابًا لملف شخصي بسيط واستعادة الحساب. يبقى محتوى التخطيط على هذا الجهاز.', localTitle: 'المتابعة محليًا', localDescription: 'لا يلزم حساب. تظل بيانات التخطيط المحلية متاحة دون اتصال.', accountTitle: 'حساب اختياري', accountDescription: 'أنشئ ملفًا شخصيًا أو سجّل الدخول. لن يؤدي ذلك إلى رفع سجلات التخطيط المحلية أو دمجها أو استبدالها.', accountUnavailable: 'خدمات الحساب غير مهيأة في هذا الإصدار. يظل الاستخدام المحلي متاحًا.', createAccount: 'إنشاء حساب', signIn: 'تسجيل الدخول', signInTitle: 'مرحبًا بعودتك', signInDescription: 'سجّل الدخول إلى حساب بلانورا الاختياري. تظل مساحة التخطيط المحلية منفصلة ومتاحة.', createTitle: 'أنشئ حسابك', createDescription: 'أنشئ ملفًا شخصيًا بسيطًا لتسجيل الدخول والاستعادة. لا يُرسل محتوى التخطيط إلى خدمة الحساب.', displayName: 'الاسم الظاهر', displayNamePlaceholder: 'الاسم الذي تفضله', email: 'البريد الإلكتروني', emailPlaceholder: 'you@example.com', password: 'كلمة المرور', confirmPassword: 'تأكيد كلمة المرور', newPassword: 'كلمة المرور الجديدة', confirmNewPassword: 'تأكيد كلمة المرور الجديدة', alreadyAccount: 'لديك حساب؟ سجّل الدخول', createInstead: 'إنشاء حساب', forgotPassword: 'هل نسيت كلمة المرور؟', recoveryEyebrow: 'استعادة الحساب', recoveryTitle: 'إعادة تعيين كلمة المرور', recoveryDescription: 'أدخل بريدك وسنطلب رسالة استعادة دون الكشف عن وجود حساب.', sendRecovery: 'إرسال تعليمات الاستعادة', secureRecovery: 'استعادة آمنة', choosePassword: 'اختر كلمة مرور جديدة', choosePasswordDescription: 'اختر كلمة مرور جديدة لحسابك. لن يغيّر ذلك بيانات التخطيط المحلية أو يحذفها.', savePassword: 'حفظ كلمة المرور الجديدة', checkEmailEyebrow: 'تحقق من بريدك', checkEmailTitle: 'خطوة أخيرة', checkEmailDescription: 'إذا كان العنوان قادرًا على استقبال الرسالة المطلوبة، فاتبع الرابط الموجود فيها للمتابعة.', inboxTitle: 'الخطوة التالية في صندوق بريدك', returnSignIn: 'العودة إلى تسجيل الدخول', recoveryValidating: 'يتحقق بلانورا من رابط الاستعادة دون عرض تفاصيل الجلسة الخاصة.', requestNewLink: 'طلب رابط جديد', issueEyebrow: 'مشكلة قابلة للحل', issueTitle: 'لنجرب مسارًا آخر', issueDescription: 'لم يكتمل طلب الحساب، لكن بيانات بلانورا المحلية آمنة وتظل متاحة.', accountOptions: 'العودة إلى خيارات الحساب', profileEyebrow: 'الملف الشخصي للحساب', editProfile: 'تعديل الملف الشخصي', profileDescription: 'هذا الملف الشخصي البسيط منفصل عن سجلات التخطيط المحلية.', profileScope: 'نطاق الملف الشخصي', saveProfile: 'حفظ الملف الشخصي', signOut: 'تسجيل الخروج', signOutTitle: 'تسجيل الخروج من حسابك؟', signOutDescription: 'تبقى بيانات التخطيط على هذا الجهاز ومتاحة بعد تسجيل الخروج.', accountLabel: 'الحساب', accountSettingsDescription: 'ميزات الحساب اختيارية وتظل منفصلة عن بيانات التخطيط المحلية.', planoraAccount: 'حساب بلانورا', localOnly: 'محلي فقط', localOnlyDescription: 'لا يلزم حساب لاستخدام علامات تبويب التخطيط الرئيسية.', emailVerified: 'تم التحقق من البريد', emailPending: 'التحقق من البريد قيد الانتظار', viewOnboarding: 'عرض المقدمة مجددًا',
    newToAccount: 'هل تستخدم ميزات الحساب لأول مرة؟',
    passwordPrivacy: 'تُرسل كلمة المرور بأمان إلى مزود الحساب ولا تُحفظ أبدًا في قاعدة بيانات التخطيط المحلية لبلانورا.',
    recoveryPrivacy: 'حفاظًا على الخصوصية، تظهر شاشة التأكيد نفسها لكل تنسيق بريد صالح.',
    showPassword: 'إظهار كلمة المرور', hidePassword: 'إخفاء كلمة المرور',
  },
  onboarding: {
    pageOneEyebrow: 'بداية أكثر هدوءًا', pageOneTitle: 'يومك مع مساحة للتنفس', pageOneDescription: 'يجمع بلانورا المهام والعادات في عرض يومي هادئ مع إبقاء مساحات التخطيط الأخرى قريبة.', pageOneDetail: 'أضف المهام وسجّل العادات دون إنشاء حساب.', pageTwoEyebrow: 'محلي بشكل افتراضي', pageTwoTitle: 'جاهز حتى دون شبكة', pageTwoDescription: 'تُحفظ قاعدة تخطيطك على هذا الجهاز وتظل متاحة دون اتصال. لا تنتظر الإجراءات المحلية خدمة الحساب.', pageTwoDetail: 'تبقى البيانات المحلية بعد إعادة تشغيل التطبيق وتظل منفصلة عن جلسات الحساب.', pageThreeEyebrow: 'الاختيار لك', pageThreeTitle: 'الحساب اختياري', pageThreeDescription: 'أنشئ حسابًا للملف الشخصي والاستعادة، أو تابع محليًا. لا يُرفع محتوى التخطيط ولا تتم مزامنته.', pageThreeDetail: 'يمكنك تسجيل الدخول لاحقًا من الإعدادات دون تغيير المعرفات المحلية.', close: 'إغلاق المقدمة', skip: 'تخطي المقدمة', step: 'الخطوة {{current}} من {{total}}', stepAnnouncement: 'الخطوة {{current}} من {{total}}. {{title}}', startLocally: 'البدء محليًا',
  },
  today: {
    greeting: 'نظرة واضحة على اليوم', subtitle: 'اختر ما يهم واترك مساحة لتغيرات اليوم.', quickPlaceholder: 'أضف مهمة لليوم', quickLabel: 'إضافة مهمة سريعة', quickHint: 'ينشئ مهمة موعدها اليوم', add: 'إضافة', progress: 'اكتمل {{completed}} من {{total}}', workload: '{{planned}} مخطط · {{remaining}} متبقٍ', nextUp: 'التالي', priority: 'الأولوية والمتأخر', remaining: 'مهام اليوم', routines: 'العادات المجدولة', agenda: 'معاينة جدول اليوم', completed: 'المكتمل', showCompleted: 'إظهار العناصر المكتملة', hideCompleted: 'إخفاء العناصر المكتملة', quietEmpty: 'لا شيء يتطلب انتباهك الآن.', noPriority: 'لا توجد مهام ذات أولوية أو متأخرة.', noRemaining: 'لا توجد مهام متبقية لليوم.', noRoutines: 'لا توجد عادات مجدولة اليوم.', noAgenda: 'لا توجد فترات زمنية مخططة بعد.', allTasks: 'كل المهام', allRoutines: 'العادات', openPlanner: 'فتح المخطط', moreActions: 'إجراءات إضافية', loading: 'جارٍ تحميل يومك.', refreshTitle: 'يحتاج يومك إلى تحديث', failed: 'تعذر تحميل يومك.', completedToday: 'اكتمل اليوم', skippedToday: 'تم التخطي اليوم', markComplete: 'وضع علامة مكتمل', markSkipped: 'وضع علامة تم التخطي', undo: 'التراجع عن التسجيل', overdue: 'متأخر', dueToday: 'موعده اليوم', unscheduled: 'صندوق الوارد',
  },
  tasks: {
    title: 'كل المهام', new: 'مهمة جديدة', details: 'تفاصيل المهمة', createDescription: 'أضف ما يهم، ثم حدد توقيته إن كان ذلك مفيدًا.', editDescription: 'حدّث المهمة دون تغيير هويتها المحلية الثابتة.', loading: 'جارٍ تحميل تفاصيل المهمة.', refreshTitle: 'تحتاج تفاصيل المهمة إلى تحديث', listRefresh: 'تحتاج قائمة المهام إلى تحديث', notLoaded: 'تعذر تحميل المهمة.', unavailable: 'المهمة غير متاحة', unavailableDescription: 'ربما حُذفت أو تغيرت. عد إلى اليوم وحدّث.', emptyTitle: 'لا توجد مهام بعد', emptyDescription: 'ستبقى الإضافات السريعة والمهام الكاملة متاحة هنا.', createAction: 'إنشاء مهمة', actions: 'إجراءات المهمة', complete: 'إكمال المهمة', reopen: 'إعادة فتح المهمة', cancel: 'إلغاء المهمة', delete: 'حذف المهمة', cancelTitle: 'إلغاء المهمة؟', cancelDescription: 'ستخرج المهمة من الأقسام اليومية النشطة ويمكن إعادة فتحها لاحقًا.', keep: 'إبقاء المهمة', deleteTitle: 'حذف المهمة؟', deleteDescription: 'يزيل هذا المهمة من العروض اليومية. لا يمكن التراجع عن هذا الإجراء هنا.', overdue: 'متأخر', upcoming: 'قادم', unscheduled: 'غير مجدول', opensDetails: 'يفتح تفاصيل المهمة', titleField: 'العنوان', notesField: 'ملاحظات', priorityField: 'الأولوية', statusField: 'الحالة', dueDate: 'تاريخ الاستحقاق', dueDateHint: 'استخدم YYYY-MM-DD أو اتركه فارغًا.', scheduledTime: 'الوقت المحدد', timeHint: 'استخدم تنسيق 24 ساعة HH:MM أو اتركه فارغًا.', priorityNone: 'بلا أولوية', priorityLow: 'أولوية منخفضة', priorityMedium: 'أولوية متوسطة', priorityHigh: 'أولوية عالية',
  },
  routines: {
    title: 'العادات', new: 'عادة جديدة', details: 'تفاصيل العادة', description: 'أنشئ إيقاعًا يوميًا أو أسبوعيًا خفيفًا دون تذكيرات أو نقاط.', loading: 'جارٍ تحميل تفاصيل العادة.', refreshTitle: 'تحتاج تفاصيل العادة إلى تحديث', listRefresh: 'تحتاج قائمة العادات إلى تحديث', notLoaded: 'تعذر تحميل العادة.', unavailable: 'العادة غير متاحة', unavailableDescription: 'عد إلى اليوم وحدّث بيانات التخطيط المحلية.', emptyTitle: 'لا توجد عادات بعد', emptyDescription: 'أنشئ إيقاعًا يوميًا أو اختر أيام الأسبوع المناسبة.', createAction: 'إنشاء عادة', opensDetails: 'يفتح تفاصيل العادة', schedule: 'الجدول', everyDay: 'كل يوم', selectedDays: 'أيام محددة', weekdays: 'أيام الأسبوع', preferredTime: 'الوقت المفضل', state: 'حالة العادة',
  },
  planner: {
    title: 'المخطط', day: 'يوم', week: 'أسبوع', previousDay: 'اليوم السابق', nextDay: 'اليوم التالي', previousWeek: 'الأسبوع السابق', nextWeek: 'الأسبوع التالي', currentWeek: 'الأسبوع الحالي', date: 'التاريخ', timeline: 'المخطط الزمني اليومي', newBlock: 'فترة زمنية جديدة', editBlock: 'تعديل الفترة الزمنية', blockDetails: 'تفاصيل الفترة الزمنية', unscheduledTasks: 'مهام غير مجدولة', scheduleTask: 'جدولة المهمة', noBlocks: 'لا توجد فترات زمنية مخططة لهذا اليوم.', noTasks: 'لكل المهام القابلة للتنفيذ فترة زمنية.', workload: 'عبء العمل', plannedMinutes: '{{duration}} مخطط', remainingCapacity: '{{duration}} متبقٍ', overCapacity: '{{duration}} فوق سعتك اليومية', withinCapacity: 'ضمن سعتك اليومية', overlapOne: '{{count}} تداخل', overlapOther: '{{count}} تداخلات', unscheduledOne: '{{count}} مهمة غير مجدولة', unscheduledOther: '{{count}} مهام غير مجدولة', blockOne: '{{count}} فترة', blockOther: '{{count}} فترات', taskOne: '{{count}} مهمة', taskOther: '{{count}} مهام', overlapWarning: 'تتداخل هذه الفترة مع فترة أخرى. يمكنك إبقاءها أو تغيير الوقت.', overlapCounted: 'تُحتسب الفترات المتداخلة منفصلة ضمن الوقت المخطط.', overloaded: 'فوق السعة', linkedTask: 'المهمة المرتبطة', linkedRoutine: 'العادة المرتبطة', removeLink: 'إزالة الارتباط', completeBlock: 'إكمال الفترة', reopenBlock: 'إعادة فتح الفترة', cancelBlock: 'إلغاء الفترة', deleteBlock: 'حذف الفترة', deleteTitle: 'حذف الفترة الزمنية؟', deleteDescription: 'يزيل هذا هذه الفترة المجدولة فقط. تبقى المهام والعادات المرتبطة متاحة.', cancelTitle: 'إلغاء الفترة الزمنية؟', cancelDescription: 'تبقى الفترات الملغاة في السجل وتتوقف عن الاحتساب ضمن السعة.', keepBlock: 'إبقاء الفترة', startTime: 'وقت البدء', endTime: 'وقت الانتهاء', titleField: 'العنوان', notesField: 'ملاحظات', statusField: 'الحالة', repeat: 'التكرار', repeatNone: 'لا يتكرر', repeatDaily: 'يوميًا', repeatWeekly: 'أسبوعيًا', repeatInterval: 'فاصل التكرار', repeatEnd: 'تاريخ انتهاء التكرار', editOccurrence: 'تعديل هذا التكرار', editFuture: 'تعديل هذا التكرار وما بعده', recurrenceBounded: 'تُجهز التكرارات ضمن نافذة متحركة من ثمانية أسابيع.', move: 'نقل أو إعادة جدولة', selectedDay: 'اليوم المحدد', currentTime: 'الوقت الحالي', capacitySummary: '{{planned}} مخطط من سعة {{capacity}}', loading: 'جارٍ تحميل جدولك.', refreshTitle: 'يحتاج جدولك إلى تحديث',
  },
  goals: {
    heading: 'الأهداف', summaryActive: '{{count}} نشطة', create: 'إنشاء هدف', edit: 'تعديل الهدف', details: 'تفاصيل الهدف', formDescription: 'حدّد اتجاهًا واضحًا دون تحويله إلى لوحة نقاط.',
    titleField: 'العنوان', descriptionField: 'الوصف', motivationField: 'لماذا يهم هذا', area: 'المجال', horizon: 'المدى', horizonMonth: 'شهر', horizonQuarter: 'ربع سنة', horizonYear: 'سنة', horizonSomeday: 'يومًا ما', targetDate: 'التاريخ المستهدف', targetDateHint: 'استخدم YYYY-MM-DD أو اتركه فارغًا.',
    status: 'الحالة', statusActive: 'نشط', statusPaused: 'متوقف مؤقتًا', statusCompleted: 'مكتمل', statusAbandoned: 'متروك', progressMethod: 'طريقة التقدم', progressMilestones: 'المراحل', progressTasks: 'المهام المرتبطة', progressManual: 'نسبة يدوية', progressNone: 'دون تقدم رقمي', manualProgress: 'التقدم اليدوي', manualHint: 'أدخل نسبة صحيحة من 0 إلى 100.',
    loading: 'جارٍ تحميل الأهداف.', refreshTitle: 'تحتاج الأهداف إلى تحديث', notLoaded: 'تعذر تحميل الأهداف. لم تتغير بياناتك المحفوظة.', unavailable: 'الهدف غير متاح', unavailableDescription: 'ربما حُذف أو تغيّر. ارجع إلى الأهداف وحدّث.', emptyTitle: 'افسح مجالًا لاتجاه ذي معنى', emptyDescription: 'أنشئ هدفًا عندما يستفيد المسار الطويل من خطوة تالية هادئة.',
    search: 'البحث في الأهداف', noMatches: 'لا توجد أهداف تطابق هذا البحث أو عامل التصفية.', filterCurrent: 'الحالية', filterCompleted: 'المكتملة', filterAll: 'الكل', activeGoals: 'الأهداف النشطة', pausedGoals: 'الأهداف المتوقفة', completedGoals: 'الأهداف المكتملة', somedayGoals: 'أهداف ليوم ما', abandonedGoals: 'الأهداف المتروكة', noTargetDate: 'لا تاريخ مستهدف', targetContext: 'المستهدف {{date}}',
    nextMilestone: 'المرحلة التالية', nextAction: 'الإجراء التالي', notStarted: 'لم يبدأ', progressCount: 'اكتمل {{completed}} من {{total}}', percentComplete: 'اكتمل {{percent}}', noNumericProgress: 'يتبع التقدم الخطوة المفيدة التالية.', opensDetails: 'يفتح تفاصيل الهدف', motivation: 'لماذا يهم',
    milestones: 'المراحل', linkedTasks: 'الإجراءات التالية المرتبطة', supportingRoutines: 'العادات الداعمة', addMilestone: 'إضافة مرحلة', linkTask: 'ربط مهمة', linkRoutine: 'ربط عادة', createTask: 'إنشاء مهمة للهدف', noMilestones: 'لا توجد مراحل بعد.', noTasks: 'لا توجد مهام مرتبطة.', noRoutines: 'لا توجد عادات داعمة بعد.',
    milestoneTitle: 'عنوان المرحلة', milestoneNotes: 'ملاحظات', milestoneDate: 'التاريخ المستهدف', milestonePending: 'قيد الانتظار', milestoneCompleted: 'مكتملة', milestoneCancelled: 'ملغاة', newMilestone: 'مرحلة جديدة', editMilestone: 'تعديل المرحلة', completeMilestone: 'إكمال المرحلة', reopenMilestone: 'إعادة فتح المرحلة', cancelMilestone: 'إلغاء المرحلة', deleteMilestone: 'حذف المرحلة', moveUp: 'نقل لأعلى', moveDown: 'نقل لأسفل', moveUpHint: 'ينقل هذه المرحلة إلى موضع أسبق في الهدف.', moveDownHint: 'ينقل هذه المرحلة إلى موضع لاحق في الهدف.',
    setNextAction: 'تعيين كإجراء تالٍ', clearNextAction: 'مسح الإجراء التالي', unlinkTask: 'إلغاء ربط المهمة', unlinkRoutine: 'إلغاء ربط العادة', routineCompletedToday: 'اكتملت اليوم', routineSkippedToday: 'تم تخطيها اليوم', routinePendingToday: 'قيد الانتظار اليوم',
    actions: 'إجراءات الهدف', pause: 'إيقاف الهدف مؤقتًا', resume: 'استئناف الهدف', complete: 'إكمال الهدف', reopen: 'إعادة فتح الهدف', abandon: 'ترك الهدف', delete: 'حذف الهدف', pauseTitle: 'إيقاف هذا الهدف مؤقتًا؟', pauseDescription: 'سيبقى الهدف متاحًا دون ظهوره كنشط.', completeTitle: 'إكمال هذا الهدف؟', completeDescription: 'يسجل هذا الاكتمال دون تغيير المهام أو العادات المرتبطة.', abandonTitle: 'ترك هذا الهدف؟', abandonDescription: 'سيغادر الهدف الأقسام الحالية وتبقى سجلاته المرتبطة سليمة.', deleteTitle: 'حذف هذا الهدف؟', deleteDescription: 'سيغادر الهدف شاشاتك. تبقى المهام والعادات المرتبطة متاحة.',
    deleteMilestoneTitle: 'حذف هذه المرحلة؟', deleteMilestoneDescription: 'يزيل هذا المرحلة من الهدف وتبقى السجلات الأخرى سليمة.', keepGoal: 'الاحتفاظ بالهدف', keepMilestone: 'الاحتفاظ بالمرحلة', chooseTask: 'اختر مهمة', chooseRoutine: 'اختر عادة', availableTasks: 'المهام القابلة للتنفيذ المتاحة', availableRoutines: 'العادات النشطة المتاحة', noAvailableTasks: 'لا توجد مهام قابلة للتنفيذ وغير مرتبطة.', noAvailableRoutines: 'لا توجد عادات نشطة وغير مرتبطة.', completionSuggestion: 'اكتملت كل المراحل. أكمل الهدف عندما تشعر أنه انتهى فعلًا.', needsAttention: 'يحتاج إلى انتباه', linkedGoal: 'الهدف: {{title}}', openGoal: 'فتح الهدف {{title}}',
  },
  settings: {
    eyebrow: 'مساحتك', title: 'الإعدادات', description: 'خصص مظهر بلانورا وسلوكه بإعدادات ميسرة منذ البداية.', language: 'اللغة', languageDescription: 'اختر لغة الواجهة لهذا الملف الشخصي المحلي.', systemLanguage: 'استخدام لغة الجهاز', directionRestart: 'أعد تشغيل بلانورا لتطبيق اتجاه الواجهة من اليمين إلى اليسار في التطبيق الأصلي. قد يعيد Expo Go ضبط هذا التفضيل؛ استخدم إصدار تطوير للتحقق من اتجاه RTL الأصلي.', planning: 'تفضيلات التخطيط', planningDescription: 'حدد سعة يومية هادئة لمقارنة عبء العمل.', capacity: 'السعة اليومية بالدقائق', capacityHint: 'اختر بين 30 و1,440 دقيقة.', saveCapacity: 'حفظ السعة', saved: 'تم حفظ التفضيل.',
  },
  storage: {
    title: 'البيانات والتخزين', description: 'توجد قاعدة تخطيطك محليًا على هذا الجهاز.', localData: 'البيانات المحلية', localReady: 'متاحة على هذا الجهاز', localPreparing: 'جارٍ إعداد الإتاحة', offline: 'الجاهزية دون اتصال', offlineReady: 'جاهز للاستخدام دون اتصال', offlinePreparing: 'جارٍ إنهاء الإعداد', state: 'حالة التخزين', ready: 'جاهز', preparing: 'جارٍ الإعداد', errorTitle: 'يحتاج التخزين المحلي إلى محاولة أخرى', retryLabel: 'إعادة محاولة إعداد التخزين المحلي',
  },
  validation: {
    goalTitle: 'أدخل عنوانًا للهدف.', milestoneTitle: 'أدخل عنوانًا للمرحلة.', percentage: 'أدخل نسبة صحيحة من 0 إلى 100.', activeArea: 'اختر مجالًا نشطًا من مساحة العمل هذه.', availableGoal: 'اختر هدفًا متاحًا من مساحة العمل هذه.',
    taskTitle: 'أدخل عنوان المهمة.', blockTitle: 'أدخل عنوان الفترة.', routineTitle: 'أدخل عنوان العادة.', titleLength: 'استخدم 200 حرف أو أقل.', notesLength: 'استخدم 4,000 حرف أو أقل.', date: 'استخدم تاريخًا صالحًا بتنسيق YYYY-MM-DD.', startDate: 'استخدم تاريخ بدء صالحًا.', endDate: 'استخدم تاريخ انتهاء صالحًا.', time: 'استخدم وقتًا صالحًا بتنسيق HH:MM.', startTime: 'استخدم وقت بدء صالحًا بتنسيق HH:MM.', endTime: 'استخدم وقت انتهاء صالحًا بتنسيق HH:MM.', endAfterStart: 'يجب أن يكون وقت الانتهاء بعد وقت البدء.', nonexistentTime: 'اختر وقتًا محليًا موجودًا في هذا التاريخ.', scheduledNeedsDate: 'اختر تاريخ استحقاق للوقت المحدد.', weekdays: 'اختر يومًا واحدًا على الأقل.', interval: 'يجب أن يكون فاصل التكرار بين 1 و365.', capacity: 'اختر عددًا صحيحًا من 30 إلى 1,440.', emailRequired: 'أدخل بريدك الإلكتروني.', emailComplete: 'أدخل عنوان بريد إلكتروني كاملًا.', passwordRequired: 'أدخل كلمة المرور.', passwordLength: 'استخدم ثمانية أحرف على الأقل.', displayNameRequired: 'أدخل اسمًا ظاهرًا.', displayNameLength: 'استخدم 60 حرفًا أو أقل.',
    passwordsMatch: 'كلمتا المرور غير متطابقتين.',
  },
  errors: {
    goalsRefresh: 'تعذر على بلانورا تحديث الأهداف. لم تتغير البيانات المحفوظة.', goalRevision: 'تغيّر هذا الهدف قبل الحفظ. حدّث وحاول مجددًا.', goalSave: 'تعذر حفظ تغيير الهدف. حدّث وحاول مجددًا.', goalUnavailable: 'لم يعد الهدف متاحًا.', goalTaskActionable: 'يمكن ربط المهام القابلة للتنفيذ فقط.', goalTaskOwned: 'تدعم هذه المهمة هدفًا آخر بالفعل.', goalTaskMissing: 'هذه المهمة غير مرتبطة بالهدف.', goalNextAction: 'اختر مهمة قابلة للتنفيذ ومرتبطة بهذا الهدف.', goalRoutineActive: 'اختر عادة نشطة من مساحة العمل هذه.',
    refreshDay: 'تعذر على بلانورا تحديث هذا اليوم. لم تتغير بياناتك المحلية المحفوظة.', revision: 'تغير هذا العنصر قبل حفظ تحديثك. حدّث وحاول مجددًا.', save: 'تعذر حفظ هذا التغيير. حدّث اليوم وحاول مجددًا.', onboardingRead: 'تعذر على بلانورا قراءة تفضيلات المقدمة. تظل بياناتك المحلية متاحة.', onboardingSave: 'تعذر على بلانورا حفظ هذا التفضيل. حاول مجددًا.', workspace: 'تعذر على بلانورا إعداد مساحة التخطيط المحلية. لم تتغير بياناتك.', generic: 'انتظر لحظة وحاول مجددًا.',
    invalidCredentials: 'لم يُقبل البريد أو كلمة المرور. تحقّق منهما وحاول مجددًا.', emailUnverified: 'أكد بريدك قبل تسجيل الدخول ثم حاول مجددًا.', emailInUse: 'لا يمكن استخدام هذا البريد لحساب جديد. حاول تسجيل الدخول.', weakPassword: 'اختر كلمة مرور أقوى من ثمانية أحرف على الأقل.', networkUnavailable: 'تعذر على بلانورا الوصول إلى خدمة الحساب. تحقق من اتصالك وحاول مجددًا.', rateLimited: 'تمت محاولات كثيرة. انتظر لحظة ثم حاول مجددًا.', expiredLink: 'رابط الاستعادة هذا لم يعد صالحًا. اطلب رابطًا جديدًا.', serviceUnavailable: 'خدمات الحساب غير متاحة مؤقتًا. بياناتك المحلية لم تتأثر.', accountUnknown: 'حدثت مشكلة في طلب الحساب. بياناتك المحلية لم تتأثر.', linkTask: 'اختر مهمة متاحة من مساحة العمل هذه.', linkRoutine: 'اختر عادة متاحة من مساحة العمل هذه.', linkEither: 'اربط مهمة أو عادة، وليس كليهما.', endBeforeStart: 'لا يمكن أن يسبق تاريخ الانتهاء تاريخ البدء.', recurrenceConflict: 'تغير هذا التكرار. حدّث وحاول مجددًا.', recurrenceWindow: 'نوافذ التكرار محدودة بـ56 يومًا.',
    scheduleRefresh: 'تعذر تحديث جدولك. لم تتغير البيانات المحلية المحفوظة.', scheduleRevision: 'تغير هذا الجدول قبل حفظ تحديثك. حدّث وحاول مجددًا.', scheduleSave: 'تعذر حفظ تغيير الجدول. حدّث وحاول مجددًا.',
  },
  placeholders: {
    goalsDescription: 'حوّل نواياك بعيدة المدى إلى مراحل واضحة وخطوات عملية تالية.', goalsEmpty: 'يبدأ التقدم الهادف هنا', goalsEmptyDescription: 'مسارات الأهداف والمراحل ومراجعات التقدم مخطط لها في مرحلة مخصصة.', insightsDescription: 'لاحظ الأنماط المفيدة مع إبقاء بياناتك الشخصية مفهومة وخاصة.', insightsEmpty: 'ستروي أنماطك قصة', insightsEmptyDescription: 'ستظهر الاتجاهات والتأملات عند توفر نشاط مفيد لتلخيصه.',
  },
} satisfies TranslationCatalog;
